{
  "SchemaVersion": 2,
  "CreatedAt": "2025-08-21T20:55:08.349953931Z",
  "ArtifactName": "/tmp/trivy-archive-U3FeyE/localhost_c20-sap_latest.tar",
  "ArtifactType": "container_image",
  "Metadata": {
    "OS": {
      "Family": "redhat",
      "Name": "8.10"
    },
    "ImageID": "sha256:39ba5b2e8a9e55598b3fa461de8726544340916cd0335c198b7cc65f93d14e61",
    "DiffIDs": [
      "sha256:2ff76d26bc63ae58824e835b041e65a91335b77fbc45c3d628f259cce07f144f",
      "sha256:5d33d880eb28756684b4a35a4128a78139d0c78643ea03e4affd5101eb3b8d02",
      "sha256:a1e1dfa9242ddce30b5f00d84de4902b99afbc62b51543f966bfdc0d4b9f78b2",
      "sha256:a5da4d9fbfe6e37d0324cf44a30ae8fcc039c971d88564e0bd4ea8faa3b1b355"
    ],
    "ImageConfig": {
      "architecture": "amd64",
      "created": "2025-04-02T12:42:28.047924486Z",
      "history": [
        {
          "created": "2025-03-13T11:34:15.047895819Z",
          "created_by": "/bin/sh -c #(nop) ADD file:04e3bb8dbcc173469bd087cd598892daaf55ccbfd076b7ba5de6c0242fb54cb0 in / ",
          "empty_layer": true
        },
        {
          "created": "2025-03-13T11:34:15.924305518Z",
          "created_by": "/bin/sh -c mv -f /etc/yum.repos.d/ubi.repo /tmp || :",
          "empty_layer": true
        },
        {
          "created": "2025-03-13T11:34:16.218900987Z",
          "created_by": "/bin/sh -c #(nop) ADD file:df13b6a4fdeac4626ab7cd7e99d16d30edc6e3e5441295ae7691bee26604a5b1 in /tmp/tls-ca-bundle.pem ",
          "empty_layer": true
        },
        {
          "created": "2025-03-13T11:34:16.605381313Z",
          "created_by": "/bin/sh -c #(nop) ADD multi:771be6fff9a852e557be99b0f12cda1b1c36d9bdb4af98b64a96cf7211fbeaa5 in /etc/yum.repos.d/ ",
          "empty_layer": true
        },
        {
          "created": "2025-03-13T11:34:16.605425709Z",
          "created_by": "/bin/sh -c #(nop) LABEL maintainer=\"Red Hat, Inc.\"",
          "empty_layer": true
        },
        {
          "created": "2025-03-13T11:34:16.605531267Z",
          "created_by": "/bin/sh -c #(nop) LABEL com.redhat.component=\"ubi8-container\"       name=\"ubi8\"       version=\"8.10\"",
          "empty_layer": true
        },
        {
          "created": "2025-03-13T11:34:16.605578667Z",
          "created_by": "/bin/sh -c #(nop) LABEL com.redhat.license_terms=\"https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI\"",
          "empty_layer": true
        },
        {
          "created": "2025-03-13T11:34:16.60561388Z",
          "created_by": "/bin/sh -c #(nop) LABEL summary=\"Provides the latest release of Red Hat Universal Base Image 8.\"",
          "empty_layer": true
        },
        {
          "created": "2025-03-13T11:34:16.605729203Z",
          "created_by": "/bin/sh -c #(nop) LABEL description=\"The Universal Base Image is designed and engineered to be the base layer for all of your containerized applications, middleware and utilities. This base image is freely redistributable, but Red Hat only supports Red Hat technologies through subscriptions for Red Hat products. This image is maintained by Red Hat and updated regularly.\"",
          "empty_layer": true
        },
        {
          "created": "2025-03-13T11:34:16.605770044Z",
          "created_by": "/bin/sh -c #(nop) LABEL io.k8s.display-name=\"Red Hat Universal Base Image 8\"",
          "empty_layer": true
        },
        {
          "created": "2025-03-13T11:34:16.605805138Z",
          "created_by": "/bin/sh -c #(nop) LABEL io.openshift.expose-services=\"\"",
          "empty_layer": true
        },
        {
          "created": "2025-03-13T11:34:16.605832194Z",
          "created_by": "/bin/sh -c #(nop) LABEL io.openshift.tags=\"base rhel8\"",
          "empty_layer": true
        },
        {
          "created": "2025-03-13T11:34:16.605846652Z",
          "created_by": "/bin/sh -c #(nop) ENV container oci",
          "empty_layer": true
        },
        {
          "created": "2025-03-13T11:34:16.605908993Z",
          "created_by": "/bin/sh -c #(nop) ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
          "empty_layer": true
        },
        {
          "created": "2025-03-13T11:34:16.60592357Z",
          "created_by": "/bin/sh -c #(nop) CMD [\"/bin/bash\"]",
          "empty_layer": true
        },
        {
          "created": "2025-03-13T11:34:17.422485596Z",
          "created_by": "/bin/sh -c rm -rf /var/log/*",
          "empty_layer": true
        },
        {
          "created": "2025-03-13T11:34:18.221313478Z",
          "created_by": "/bin/sh -c mkdir -p /var/log/rhsm",
          "empty_layer": true
        },
        {
          "created": "2025-03-13T11:34:18.491113876Z",
          "created_by": "/bin/sh -c #(nop) ADD file:b2504ac56e42d221cb97ae63b245e52d960e7417b4da4abdda91f820a1dd5708 in /root/buildinfo/content_manifests/ubi8-container-8.10-1184.1741863532.json ",
          "empty_layer": true
        },
        {
          "created": "2025-03-13T11:34:18.799596697Z",
          "created_by": "/bin/sh -c #(nop) ADD file:fc0e17da15a231b0a8534ffb8ef0fbf087a6da1ff35f8721112100089ce4afc5 in /root/buildinfo/Dockerfile-ubi8-8.10-1184.1741863532 ",
          "empty_layer": true
        },
        {
          "created": "2025-03-13T11:34:18.799816644Z",
          "created_by": "/bin/sh -c #(nop) LABEL \"release\"=\"1184.1741863532\" \"distribution-scope\"=\"public\" \"vendor\"=\"Red Hat, Inc.\" \"build-date\"=\"2025-03-13T10:59:43\" \"architecture\"=\"x86_64\" \"vcs-type\"=\"git\" \"vcs-ref\"=\"967861a8dbbb288b8cec9f1fee7ccbf6c7ee9a20\" \"io.k8s.description\"=\"The Universal Base Image is designed and engineered to be the base layer for all of your containerized applications, middleware and utilities. This base image is freely redistributable, but Red Hat only supports Red Hat technologies through subscriptions for Red Hat products. This image is maintained by Red Hat and updated regularly.\" \"url\"=\"https://access.redhat.com/containers/#/registry.access.redhat.com/ubi8/images/8.10-1184.1741863532\"",
          "empty_layer": true
        },
        {
          "created": "2025-03-13T11:34:19.678426013Z",
          "created_by": "/bin/sh -c rm -f '/etc/yum.repos.d/odcs-3978716-29051.repo' '/etc/yum.repos.d/rhel-8.10-compose-0e878.repo'",
          "empty_layer": true
        },
        {
          "created": "2025-03-13T11:34:20.729464853Z",
          "created_by": "/bin/sh -c rm -f /tmp/tls-ca-bundle.pem",
          "empty_layer": true
        },
        {
          "created": "2025-03-13T11:34:23.860418304Z",
          "created_by": "/bin/sh -c mv -fZ /tmp/ubi.repo /etc/yum.repos.d/ubi.repo || :"
        },
        {
          "created": "2025-04-02T12:41:03.839814698Z",
          "created_by": "/bin/sh -c #(nop) COPY multi:709fe3d038ecc187eb1c532c16d221d8e243694fafe99b65fa64ba9b5fff3020 in /templates/ ",
          "comment": "FROM localhost/ubi8:8.10"
        },
        {
          "created": "2025-04-02T12:41:04.254836521Z",
          "created_by": "/bin/sh -c #(nop) COPY multi:a8317283ad3b003b9fd4e5c80baa1b0a9cf0d6655b2b48b8df429cff7c3c7e2e in /sap_scripts/ ",
          "comment": "FROM 30e54cf0d88c"
        },
        {
          "created": "2025-04-02T12:42:26.026821115Z",
          "created_by": "/bin/sh -c  sed -i \"s/enabled=0/enabled=1/\" /etc/dnf/plugins/subscription-manager.conf \u0026\u0026       chmod +x /sap_scripts/entrypoint.sh \u0026\u0026      chmod +x /sap_scripts/hana_install.sh \u0026\u0026      chmod +x /sap_scripts/monitor.sh \u0026\u0026      chmod +x /templates/* \u0026\u0026      chmod +x /sap_scripts/sap_inst.sh \u0026\u0026      chmod +x /sap_scripts/sap_start.sh \u0026\u0026      mkdir /usr/sap \u0026\u0026      touch /usr/sap/.novolume \u0026\u0026      mkdir /hana \u0026\u0026      touch /hana/.novolume \u0026\u0026      mkdir /backup \u0026\u0026      touch /backup/.novolume \u0026\u0026      mkdir /sapmnt \u0026\u0026      touch /sapmnt/.novolume \u0026\u0026      mkdir /var/lib/hdb \u0026\u0026      mkdir -p /var/opt/.hdb \u0026\u0026      mkdir -p /installation_files \u0026\u0026      ln -s /etc/pki/entitlement-host /etc/pki/entitlement \u0026\u0026      ln /etc/rhsm-host /etc/rhsm \u0026\u0026      rm /etc/yum.repos.d/ubi.repo  \u0026\u0026      ln -s /run/secrets/redhat.repo /etc/yum.repos.d/redhat.repo \u0026\u0026      dnf update -y \u0026\u0026      dnf install -y --nodocs uuid libicu libatomic libaio expect bind-utils psmisc libtool-ltdl hostname libnsl.so.2 python3.12 uuidd glib2 tcsh numactl net-tools iproute iputils wget nano curl ncurses policycoreutils compat-sap-c++-11.x86_64 procps \u0026\u0026      dnf clean all \u0026\u0026      mkdir /saprpms \u0026\u0026      rm -rf /saprpms/ \u0026\u0026      echo root:changeme | chpasswd \u0026\u0026      useradd sapuser \u0026\u0026      useradd sapadm \u0026\u0026      sed -i \"s/enabled=1/enabled=0/\" /etc/dnf/plugins/subscription-manager.conf ",
          "comment": "FROM 6c0b6deaa276"
        },
        {
          "created": "2025-04-02T12:42:27.423051201Z",
          "created_by": "/bin/sh -c #(nop) EXPOSE 8000",
          "comment": "FROM a2fab519ee4d",
          "empty_layer": true
        },
        {
          "created": "2025-04-02T12:42:27.46300853Z",
          "created_by": "/bin/sh -c #(nop) EXPOSE 44300",
          "comment": "FROM 196eb2f75f49",
          "empty_layer": true
        },
        {
          "created": "2025-04-02T12:42:27.501694376Z",
          "created_by": "/bin/sh -c #(nop) EXPOSE 3300",
          "comment": "FROM 7d00b603aee6",
          "empty_layer": true
        },
        {
          "created": "2025-04-02T12:42:27.541306106Z",
          "created_by": "/bin/sh -c #(nop) EXPOSE 3200",
          "comment": "FROM 09d1a38927bd",
          "empty_layer": true
        },
        {
          "created": "2025-04-02T12:42:27.580175554Z",
          "created_by": "/bin/sh -c #(nop) EXPOSE 4237",
          "comment": "FROM 6e070ecf2176",
          "empty_layer": true
        },
        {
          "created": "2025-04-02T12:42:27.619023108Z",
          "created_by": "/bin/sh -c #(nop) EXPOSE 50000",
          "comment": "FROM 876dda8840f1",
          "empty_layer": true
        },
        {
          "created": "2025-04-02T12:42:27.658218141Z",
          "created_by": "/bin/sh -c #(nop) EXPOSE 44300",
          "comment": "FROM 028ade57ed62",
          "empty_layer": true
        },
        {
          "created": "2025-04-02T12:42:27.698552391Z",
          "created_by": "/bin/sh -c #(nop) EXPOSE 1129",
          "comment": "FROM b1cf4155f08c",
          "empty_layer": true
        },
        {
          "created": "2025-04-02T12:42:27.739031696Z",
          "created_by": "/bin/sh -c #(nop) EXPOSE 1128",
          "comment": "FROM 880b56685144",
          "empty_layer": true
        },
        {
          "created": "2025-04-02T12:42:27.777594675Z",
          "created_by": "/bin/sh -c #(nop) EXPOSE 3601",
          "comment": "FROM f3dc63b3e140",
          "empty_layer": true
        },
        {
          "created": "2025-04-02T12:42:27.817262237Z",
          "created_by": "/bin/sh -c #(nop) EXPOSE 30215",
          "comment": "FROM 1d7e61c9ff42",
          "empty_layer": true
        },
        {
          "created": "2025-04-02T12:42:27.855201378Z",
          "created_by": "/bin/sh -c #(nop) EXPOSE 30213",
          "comment": "FROM 6826a3f3bad7",
          "empty_layer": true
        },
        {
          "created": "2025-04-02T12:42:27.894480126Z",
          "created_by": "/bin/sh -c #(nop) EXPOSE 40000",
          "comment": "FROM 9bc9c4863ac8",
          "empty_layer": true
        },
        {
          "created": "2025-04-02T12:42:27.931830636Z",
          "created_by": "/bin/sh -c #(nop) ENV container oci",
          "comment": "FROM 046c3a51802d",
          "empty_layer": true
        },
        {
          "created": "2025-04-02T12:42:27.970047767Z",
          "created_by": "/bin/sh -c #(nop) ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
          "comment": "FROM 316ad575f5f0",
          "empty_layer": true
        },
        {
          "created": "2025-04-02T12:42:28.009642748Z",
          "created_by": "/bin/sh -c #(nop) ENTRYPOINT [\"/sap_scripts/entrypoint.sh\"]",
          "comment": "FROM 819d7af0be27",
          "empty_layer": true
        },
        {
          "created": "2025-04-02T12:42:28.048345095Z",
          "created_by": "/bin/sh -c #(nop) CMD [\"INIT=START\"]",
          "comment": "FROM ce700e6a36c4",
          "empty_layer": true
        }
      ],
      "os": "linux",
      "rootfs": {
        "type": "layers",
        "diff_ids": [
          "sha256:2ff76d26bc63ae58824e835b041e65a91335b77fbc45c3d628f259cce07f144f",
          "sha256:5d33d880eb28756684b4a35a4128a78139d0c78643ea03e4affd5101eb3b8d02",
          "sha256:a1e1dfa9242ddce30b5f00d84de4902b99afbc62b51543f966bfdc0d4b9f78b2",
          "sha256:a5da4d9fbfe6e37d0324cf44a30ae8fcc039c971d88564e0bd4ea8faa3b1b355"
        ]
      },
      "config": {
        "Cmd": [
          "INIT=START"
        ],
        "Entrypoint": [
          "/sap_scripts/entrypoint.sh"
        ],
        "Env": [
          "container=oci",
          "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        ],
        "Labels": {
          "architecture": "x86_64",
          "build-date": "2025-03-13T10:59:43",
          "com.redhat.component": "ubi8-container",
          "com.redhat.license_terms": "https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI",
          "description": "The Universal Base Image is designed and engineered to be the base layer for all of your containerized applications, middleware and utilities. This base image is freely redistributable, but Red Hat only supports Red Hat technologies through subscriptions for Red Hat products. This image is maintained by Red Hat and updated regularly.",
          "distribution-scope": "public",
          "io.buildah.version": "1.33.12",
          "io.k8s.description": "The Universal Base Image is designed and engineered to be the base layer for all of your containerized applications, middleware and utilities. This base image is freely redistributable, but Red Hat only supports Red Hat technologies through subscriptions for Red Hat products. This image is maintained by Red Hat and updated regularly.",
          "io.k8s.display-name": "Red Hat Universal Base Image 8",
          "io.openshift.expose-services": "",
          "io.openshift.tags": "base rhel8",
          "maintainer": "Red Hat, Inc.",
          "name": "ubi8",
          "release": "1184.1741863532",
          "summary": "Provides the latest release of Red Hat Universal Base Image 8.",
          "url": "https://access.redhat.com/containers/#/registry.access.redhat.com/ubi8/images/8.10-1184.1741863532",
          "vcs-ref": "967861a8dbbb288b8cec9f1fee7ccbf6c7ee9a20",
          "vcs-type": "git",
          "vendor": "Red Hat, Inc.",
          "version": "8.10"
        },
        "ExposedPorts": {
          "1128/tcp": {},
          "1129/tcp": {},
          "30213/tcp": {},
          "30215/tcp": {},
          "3200/tcp": {},
          "3300/tcp": {},
          "3601/tcp": {},
          "40000/tcp": {},
          "4237/tcp": {},
          "44300/tcp": {},
          "50000/tcp": {},
          "8000/tcp": {}
        }
      }
    }
  },
  "Results": [
    {
      "Target": "/tmp/trivy-archive-U3FeyE/localhost_c20-sap_latest.tar (redhat 8.10)",
      "Class": "os-pkgs",
      "Type": "redhat",
      "Vulnerabilities": [
        {
          "VulnerabilityID": "CVE-2025-5914",
          "PkgID": "libarchive@3.3.3-5.el8.x86_64",
          "PkgName": "libarchive",
          "PkgIdentifier": {
            "PURL": "pkg:rpm/redhat/libarchive@3.3.3-5.el8?arch=x86_64\u0026distro=redhat-8.10",
            "UID": "63923a0b4b5beea2"
          },
          "InstalledVersion": "3.3.3-5.el8",
          "Status": "affected",
          "Layer": {
            "DiffID": "sha256:2ff76d26bc63ae58824e835b041e65a91335b77fbc45c3d628f259cce07f144f"
          },
          "SeveritySource": "redhat",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2025-5914",
          "Title": "libarchive: Double free at archive_read_format_rar_seek_data() in archive_read_support_format_rar.c",
          "Description": "A vulnerability has been identified in the libarchive library, specifically within the archive_read_format_rar_seek_data() function. This flaw involves an integer overflow that can ultimately lead to a double-free condition. Exploiting a double-free vulnerability can result in memory corruption, enabling an attacker to execute arbitrary code or cause a denial-of-service condition.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-415"
          ],
          "VendorSeverity": {
            "amazon": 3,
            "nvd": 4,
            "photon": 3,
            "redhat": 3,
            "ubuntu": 2
          },
          "CVSS": {
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 9.8
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:R/S:U/C:H/I:H/A:H",
              "V3Score": 7.3
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2025-5914",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370861",
            "https://github.com/libarchive/libarchive/pull/2598",
            "https://github.com/libarchive/libarchive/pull/2598/commits/196029dd0a17cd17c916eada9085839032b76ec9",
            "https://github.com/libarchive/libarchive/releases/tag/v3.8.0",
            "https://nvd.nist.gov/vuln/detail/CVE-2025-5914",
            "https://ubuntu.com/security/notices/USN-7601-1",
            "https://www.cve.org/CVERecord?id=CVE-2025-5914"
          ],
          "PublishedDate": "2025-06-09T20:15:26.123Z",
          "LastModifiedDate": "2025-08-12T11:15:27.42Z"
        },
        {
          "VulnerabilityID": "CVE-2025-49794",
          "VendorIDs": [
            "RHSA-2025:10698"
          ],
          "PkgID": "libxml2@2.9.7-19.el8_10.x86_64",
          "PkgName": "libxml2",
          "PkgIdentifier": {
            "PURL": "pkg:rpm/redhat/libxml2@2.9.7-19.el8_10?arch=x86_64\u0026distro=redhat-8.10",
            "UID": "497e31bcff69ad56"
          },
          "InstalledVersion": "2.9.7-19.el8_10",
          "FixedVersion": "2.9.7-21.el8_10.1",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:2ff76d26bc63ae58824e835b041e65a91335b77fbc45c3d628f259cce07f144f"
          },
          "SeveritySource": "redhat",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2025-49794",
          "Title": "libxml: Heap use after free (UAF) leads to Denial of service (DoS)",
          "Description": "A use-after-free vulnerability was found in libxml2. This issue occurs when parsing XPath elements under certain circumstances when the XML schematron has the \u003csch:name path=\"...\"/\u003e schema elements. This flaw allows a malicious actor to craft a malicious XML document used as input for libxml, resulting in the program's crash using libxml or other possible undefined behaviors.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-825"
          ],
          "VendorSeverity": {
            "alma": 3,
            "amazon": 3,
            "azure": 4,
            "cbl-mariner": 4,
            "oracle-oval": 3,
            "photon": 4,
            "redhat": 3,
            "rocky": 3
          },
          "CVSS": {
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:H",
              "V3Score": 9.1
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2025:10630",
            "https://access.redhat.com/errata/RHSA-2025:10698",
            "https://access.redhat.com/errata/RHSA-2025:10699",
            "https://access.redhat.com/errata/RHSA-2025:11580",
            "https://access.redhat.com/errata/RHSA-2025:12098",
            "https://access.redhat.com/errata/RHSA-2025:12099",
            "https://access.redhat.com/errata/RHSA-2025:12199",
            "https://access.redhat.com/errata/RHSA-2025:12237",
            "https://access.redhat.com/errata/RHSA-2025:12239",
            "https://access.redhat.com/errata/RHSA-2025:12240",
            "https://access.redhat.com/errata/RHSA-2025:12241",
            "https://access.redhat.com/errata/RHSA-2025:13335",
            "https://access.redhat.com/security/cve/CVE-2025-49794",
            "https://bugzilla.redhat.com/2372373",
            "https://bugzilla.redhat.com/2372385",
            "https://bugzilla.redhat.com/2372406",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2372373",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2372385",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2372406",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-49794",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-49796",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-6021",
            "https://errata.almalinux.org/9/ALSA-2025-10699.html",
            "https://errata.rockylinux.org/RLSA-2025:10698",
            "https://linux.oracle.com/cve/CVE-2025-49794.html",
            "https://linux.oracle.com/errata/ELSA-2025-12240.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2025-49794",
            "https://www.cve.org/CVERecord?id=CVE-2025-49794"
          ],
          "PublishedDate": "2025-06-16T16:15:18.997Z",
          "LastModifiedDate": "2025-08-07T09:15:27.75Z"
        },
        {
          "VulnerabilityID": "CVE-2025-49796",
          "VendorIDs": [
            "RHSA-2025:10698"
          ],
          "PkgID": "libxml2@2.9.7-19.el8_10.x86_64",
          "PkgName": "libxml2",
          "PkgIdentifier": {
            "PURL": "pkg:rpm/redhat/libxml2@2.9.7-19.el8_10?arch=x86_64\u0026distro=redhat-8.10",
            "UID": "497e31bcff69ad56"
          },
          "InstalledVersion": "2.9.7-19.el8_10",
          "FixedVersion": "2.9.7-21.el8_10.1",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:2ff76d26bc63ae58824e835b041e65a91335b77fbc45c3d628f259cce07f144f"
          },
          "SeveritySource": "redhat",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2025-49796",
          "Title": "libxml: Type confusion leads to Denial of service (DoS)",
          "Description": "A vulnerability was found in libxml2. Processing certain sch:name elements from the input XML file can trigger a memory corruption issue. This flaw allows an attacker to craft a malicious XML input file that can lead libxml to crash, resulting in a denial of service or other possible undefined behavior due to sensitive data being corrupted in memory.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-125"
          ],
          "VendorSeverity": {
            "alma": 3,
            "amazon": 3,
            "azure": 4,
            "cbl-mariner": 4,
            "oracle-oval": 3,
            "photon": 4,
            "redhat": 3,
            "rocky": 3
          },
          "CVSS": {
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:H",
              "V3Score": 9.1
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2025:10630",
            "https://access.redhat.com/errata/RHSA-2025:10698",
            "https://access.redhat.com/errata/RHSA-2025:10699",
            "https://access.redhat.com/errata/RHSA-2025:11580",
            "https://access.redhat.com/errata/RHSA-2025:12098",
            "https://access.redhat.com/errata/RHSA-2025:12099",
            "https://access.redhat.com/errata/RHSA-2025:12199",
            "https://access.redhat.com/errata/RHSA-2025:12237",
            "https://access.redhat.com/errata/RHSA-2025:12239",
            "https://access.redhat.com/errata/RHSA-2025:12240",
            "https://access.redhat.com/errata/RHSA-2025:12241",
            "https://access.redhat.com/errata/RHSA-2025:13267",
            "https://access.redhat.com/errata/RHSA-2025:13335",
            "https://access.redhat.com/security/cve/CVE-2025-49796",
            "https://bugzilla.redhat.com/2372373",
            "https://bugzilla.redhat.com/2372385",
            "https://bugzilla.redhat.com/2372406",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2372373",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2372385",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2372406",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-49794",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-49796",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-6021",
            "https://errata.almalinux.org/9/ALSA-2025-10699.html",
            "https://errata.rockylinux.org/RLSA-2025:10698",
            "https://linux.oracle.com/cve/CVE-2025-49796.html",
            "https://linux.oracle.com/errata/ELSA-2025-12240.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2025-49796",
            "https://www.cve.org/CVERecord?id=CVE-2025-49796"
          ],
          "PublishedDate": "2025-06-16T16:15:19.37Z",
          "LastModifiedDate": "2025-08-07T09:15:27.99Z"
        },
        {
          "VulnerabilityID": "CVE-2025-7425",
          "VendorIDs": [
            "RHSA-2025:12450"
          ],
          "PkgID": "libxml2@2.9.7-19.el8_10.x86_64",
          "PkgName": "libxml2",
          "PkgIdentifier": {
            "PURL": "pkg:rpm/redhat/libxml2@2.9.7-19.el8_10?arch=x86_64\u0026distro=redhat-8.10",
            "UID": "497e31bcff69ad56"
          },
          "InstalledVersion": "2.9.7-19.el8_10",
          "FixedVersion": "2.9.7-21.el8_10.2",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:2ff76d26bc63ae58824e835b041e65a91335b77fbc45c3d628f259cce07f144f"
          },
          "SeveritySource": "redhat",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2025-7425",
          "Title": "libxslt: Heap Use-After-Free in libxslt caused by atype corruption in xmlAttrPtr",
          "Description": "A flaw was found in libxslt where the attribute type, atype, flags are modified in a way that corrupts internal memory management. When XSLT functions, such as the key() process, result in tree fragments, this corruption prevents the proper cleanup of ID attributes. As a result, the system may access freed memory, causing crashes or enabling attackers to trigger heap corruption.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-416"
          ],
          "VendorSeverity": {
            "alma": 3,
            "oracle-oval": 3,
            "redhat": 3
          },
          "CVSS": {
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:L/AC:H/PR:N/UI:N/S:C/C:N/I:H/A:H",
              "V3Score": 7.8
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2025:12447",
            "https://access.redhat.com/errata/RHSA-2025:12450",
            "https://access.redhat.com/errata/RHSA-2025:13267",
            "https://access.redhat.com/errata/RHSA-2025:13308",
            "https://access.redhat.com/errata/RHSA-2025:13309",
            "https://access.redhat.com/errata/RHSA-2025:13310",
            "https://access.redhat.com/errata/RHSA-2025:13311",
            "https://access.redhat.com/errata/RHSA-2025:13312",
            "https://access.redhat.com/errata/RHSA-2025:13313",
            "https://access.redhat.com/errata/RHSA-2025:13314",
            "https://access.redhat.com/errata/RHSA-2025:13335",
            "https://access.redhat.com/errata/RHSA-2025:13464",
            "https://access.redhat.com/errata/RHSA-2025:13622",
            "https://access.redhat.com/security/cve/CVE-2025-7425",
            "https://bugzilla.redhat.com/2379274",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2379274",
            "https://errata.almalinux.org/9/ALSA-2025-12447.html",
            "https://gitlab.gnome.org/GNOME/libxslt/-/issues/140",
            "https://linux.oracle.com/cve/CVE-2025-7425.html",
            "https://linux.oracle.com/errata/ELSA-2025-12450.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2025-7425",
            "https://www.cve.org/CVERecord?id=CVE-2025-7425"
          ],
          "PublishedDate": "2025-07-10T14:15:27.877Z",
          "LastModifiedDate": "2025-08-11T15:15:28.383Z"
        },
        {
          "VulnerabilityID": "CVE-2025-6020",
          "VendorIDs": [
            "RHSA-2025:10027"
          ],
          "PkgID": "pam@1.3.1-36.el8_10.x86_64",
          "PkgName": "pam",
          "PkgIdentifier": {
            "PURL": "pkg:rpm/redhat/pam@1.3.1-36.el8_10?arch=x86_64\u0026distro=redhat-8.10",
            "UID": "6000e490c535e39e"
          },
          "InstalledVersion": "1.3.1-36.el8_10",
          "FixedVersion": "1.3.1-37.el8_10",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:2ff76d26bc63ae58824e835b041e65a91335b77fbc45c3d628f259cce07f144f"
          },
          "SeveritySource": "redhat",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2025-6020",
          "Title": "linux-pam: Linux-pam directory Traversal",
          "Description": "A flaw was found in linux-pam. The module pam_namespace may use access user-controlled paths without proper protection, allowing local users to elevate their privileges to root via multiple symlink attacks and race conditions.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-22"
          ],
          "VendorSeverity": {
            "alma": 3,
            "amazon": 2,
            "azure": 3,
            "cbl-mariner": 3,
            "oracle-oval": 3,
            "redhat": 3,
            "rocky": 3,
            "ubuntu": 2
          },
          "CVSS": {
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 7.8
            }
          },
          "References": [
            "http://www.openwall.com/lists/oss-security/2025/06/17/1",
            "https://access.redhat.com/errata/RHSA-2025:10024",
            "https://access.redhat.com/errata/RHSA-2025:10027",
            "https://access.redhat.com/errata/RHSA-2025:10180",
            "https://access.redhat.com/errata/RHSA-2025:10354",
            "https://access.redhat.com/errata/RHSA-2025:10357",
            "https://access.redhat.com/errata/RHSA-2025:10358",
            "https://access.redhat.com/errata/RHSA-2025:10359",
            "https://access.redhat.com/errata/RHSA-2025:10361",
            "https://access.redhat.com/errata/RHSA-2025:10362",
            "https://access.redhat.com/errata/RHSA-2025:10735",
            "https://access.redhat.com/errata/RHSA-2025:10823",
            "https://access.redhat.com/errata/RHSA-2025:11386",
            "https://access.redhat.com/errata/RHSA-2025:11487",
            "https://access.redhat.com/errata/RHSA-2025:9526",
            "https://access.redhat.com/security/cve/CVE-2025-6020",
            "https://bugzilla.redhat.com/2372512",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2372512",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-6020",
            "https://errata.almalinux.org/9/ALSA-2025-9526.html",
            "https://errata.rockylinux.org/RLSA-2025:10027",
            "https://linux.oracle.com/cve/CVE-2025-6020.html",
            "https://linux.oracle.com/errata/ELSA-2025-9526.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2025-6020",
            "https://ubuntu.com/security/notices/USN-7580-1",
            "https://www.cve.org/CVERecord?id=CVE-2025-6020",
            "https://www.openwall.com/lists/oss-security/2025/06/17/1"
          ],
          "PublishedDate": "2025-06-17T13:15:21.66Z",
          "LastModifiedDate": "2025-07-21T20:15:42.027Z"
        },
        {
          "VulnerabilityID": "CVE-2025-8941",
          "PkgID": "pam@1.3.1-36.el8_10.x86_64",
          "PkgName": "pam",
          "PkgIdentifier": {
            "PURL": "pkg:rpm/redhat/pam@1.3.1-36.el8_10?arch=x86_64\u0026distro=redhat-8.10",
            "UID": "6000e490c535e39e"
          },
          "InstalledVersion": "1.3.1-36.el8_10",
          "Status": "affected",
          "Layer": {
            "DiffID": "sha256:2ff76d26bc63ae58824e835b041e65a91335b77fbc45c3d628f259cce07f144f"
          },
          "SeveritySource": "redhat",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2025-8941",
          "Title": "linux-pam: Incomplete fix for CVE-2025-6020",
          "Description": "A flaw was found in linux-pam. The pam_namespace module may improperly handle user-controlled paths, allowing local users to exploit symlink attacks and race conditions to elevate their privileges to root. This CVE provides a \"complete\" fix for CVE-2025-6020.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-22"
          ],
          "VendorSeverity": {
            "redhat": 3
          },
          "CVSS": {
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 7.8
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2025-8941",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2388220",
            "https://nvd.nist.gov/vuln/detail/CVE-2025-8941",
            "https://www.cve.org/CVERecord?id=CVE-2025-8941"
          ],
          "PublishedDate": "2025-08-13T15:15:41.873Z",
          "LastModifiedDate": "2025-08-13T17:33:46.673Z"
        },
        {
          "VulnerabilityID": "CVE-2024-12718",
          "VendorIDs": [
            "RHSA-2025:10128"
          ],
          "PkgID": "platform-python@3.6.8-69.el8_10.x86_64",
          "PkgName": "platform-python",
          "PkgIdentifier": {
            "PURL": "pkg:rpm/redhat/platform-python@3.6.8-69.el8_10?arch=x86_64\u0026distro=redhat-8.10",
            "UID": "8ca2b48af17f25c6"
          },
          "InstalledVersion": "3.6.8-69.el8_10",
          "FixedVersion": "3.6.8-70.el8_10",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:2ff76d26bc63ae58824e835b041e65a91335b77fbc45c3d628f259cce07f144f"
          },
          "SeveritySource": "redhat",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-12718",
          "Title": "cpython: python: Bypass extraction filter to modify file metadata outside extraction directory",
          "Description": "Allows modifying some file metadata (e.g. last modified) with filter=\"data\" or file permissions (chmod) with filter=\"tar\" of files outside the extraction directory.\nYou are affected by this vulnerability if using the tarfile module to extract untrusted tar archives using TarFile.extractall() or TarFile.extract() using the filter= parameter with a value of \"data\" or \"tar\". See the tarfile  extraction filters documentation https://docs.python.org/3/library/tarfile.html#tarfile-extraction-filter  for more information. Only Python versions 3.12 or later are affected by these vulnerabilities, earlier versions don't include the extraction filter feature.\n\nNote that for Python 3.14 or later the default value of filter= changed from \"no filtering\" to `\"data\", so if you are relying on this new default behavior then your usage is also affected.\n\nNote that none of these vulnerabilities significantly affect the installation of source distributions which are tar archives as source distributions already allow arbitrary code execution during the build process. However when evaluating source distributions it's important to avoid installing source distributions with suspicious links.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-22"
          ],
          "VendorSeverity": {
            "alma": 3,
            "amazon": 3,
            "bitnami": 2,
            "cbl-mariner": 2,
            "oracle-oval": 3,
            "photon": 2,
            "redhat": 3,
            "rocky": 3,
            "ubuntu": 2
          },
          "CVSS": {
            "bitnami": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
              "V3Score": 5.3
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:H/I:H/A:L",
              "V3Score": 7.6
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2025:10189",
            "https://access.redhat.com/security/cve/CVE-2024-12718",
            "https://bugzilla.redhat.com/2370010",
            "https://bugzilla.redhat.com/2370013",
            "https://bugzilla.redhat.com/2370014",
            "https://bugzilla.redhat.com/2370016",
            "https://bugzilla.redhat.com/2372426",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370010",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370013",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370014",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370016",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2372426",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-12718",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4138",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4330",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4435",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4517",
            "https://errata.almalinux.org/9/ALSA-2025-10189.html",
            "https://errata.rockylinux.org/RLSA-2025:10031",
            "https://gist.github.com/sethmlarson/52398e33eff261329a0180ac1d54f42f",
            "https://github.com/python/cpython/commit/19de092debb3d7e832e5672cc2f7b788d35951da",
            "https://github.com/python/cpython/commit/28463dba112af719df1e8b0391c46787ad756dd9",
            "https://github.com/python/cpython/commit/3612d8f51741b11f36f8fb0494d79086bac9390a",
            "https://github.com/python/cpython/commit/4633f3f497b1ff70e4a35b6fe2c907cbe2d4cb2e",
            "https://github.com/python/cpython/commit/98016f7c92aa4c1232c68bac1ed6646db31782ec",
            "https://github.com/python/cpython/commit/9c1110ef6652687d7c55f590f909720eddde965a",
            "https://github.com/python/cpython/commit/9e0ac76d96cf80b49055f6d6b9a6763fb9215c2a",
            "https://github.com/python/cpython/commit/aa9eb5f757ceff461e6e996f12c89e5d9b583b01",
            "https://github.com/python/cpython/commit/dd8f187d0746da151e0025c51680979ac5b4cfb1",
            "https://github.com/python/cpython/issues/127987",
            "https://github.com/python/cpython/issues/135034",
            "https://github.com/python/cpython/pull/135037",
            "https://linux.oracle.com/cve/CVE-2024-12718.html",
            "https://linux.oracle.com/errata/ELSA-2025-10189.html",
            "https://mail.python.org/archives/list/security-announce@python.org/thread/MAXIJJCUUMCL7ATZNDVEGGHUMQMUUKLG/",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-12718",
            "https://ubuntu.com/security/notices/USN-7583-1",
            "https://www.cve.org/CVERecord?id=CVE-2024-12718"
          ],
          "PublishedDate": "2025-06-03T13:15:20.183Z",
          "LastModifiedDate": "2025-07-24T16:15:29.157Z"
        },
        {
          "VulnerabilityID": "CVE-2025-4138",
          "VendorIDs": [
            "RHSA-2025:10128"
          ],
          "PkgID": "platform-python@3.6.8-69.el8_10.x86_64",
          "PkgName": "platform-python",
          "PkgIdentifier": {
            "PURL": "pkg:rpm/redhat/platform-python@3.6.8-69.el8_10?arch=x86_64\u0026distro=redhat-8.10",
            "UID": "8ca2b48af17f25c6"
          },
          "InstalledVersion": "3.6.8-69.el8_10",
          "FixedVersion": "3.6.8-70.el8_10",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:2ff76d26bc63ae58824e835b041e65a91335b77fbc45c3d628f259cce07f144f"
          },
          "SeveritySource": "redhat",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2025-4138",
          "Title": "cpython: python: Bypassing extraction filter to create symlinks to arbitrary targets outside extraction directory",
          "Description": "Allows the extraction filter to be ignored, allowing symlink targets to point outside the destination directory, and the modification of some file metadata.\n\n\nYou are affected by this vulnerability if using the tarfile module to extract untrusted tar archives using TarFile.extractall() or TarFile.extract() using the filter= parameter with a value of \"data\" or \"tar\". See the tarfile  extraction filters documentation https://docs.python.org/3/library/tarfile.html#tarfile-extraction-filter  for more information.\n\nNote that for Python 3.14 or later the default value of filter= changed from \"no filtering\" to `\"data\", so if you are relying on this new default behavior then your usage is also affected.\n\nNote that none of these vulnerabilities significantly affect the installation of source distributions which are tar archives as source distributions already allow arbitrary code execution during the build process. However when evaluating source distributions it's important to avoid installing source distributions with suspicious links.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-22"
          ],
          "VendorSeverity": {
            "alma": 3,
            "amazon": 3,
            "bitnami": 3,
            "cbl-mariner": 3,
            "oracle-oval": 3,
            "photon": 3,
            "redhat": 3,
            "rocky": 3,
            "ubuntu": 2
          },
          "CVSS": {
            "bitnami": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
              "V3Score": 7.5
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2025:10189",
            "https://access.redhat.com/security/cve/CVE-2025-4138",
            "https://bugzilla.redhat.com/2370010",
            "https://bugzilla.redhat.com/2370013",
            "https://bugzilla.redhat.com/2370014",
            "https://bugzilla.redhat.com/2370016",
            "https://bugzilla.redhat.com/2372426",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370010",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370013",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370014",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370016",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2372426",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-12718",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4138",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4330",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4435",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4517",
            "https://errata.almalinux.org/9/ALSA-2025-10189.html",
            "https://errata.rockylinux.org/RLSA-2025:10031",
            "https://gist.github.com/sethmlarson/52398e33eff261329a0180ac1d54f42f",
            "https://github.com/python/cpython/commit/19de092debb3d7e832e5672cc2f7b788d35951da",
            "https://github.com/python/cpython/commit/28463dba112af719df1e8b0391c46787ad756dd9",
            "https://github.com/python/cpython/commit/3612d8f51741b11f36f8fb0494d79086bac9390a",
            "https://github.com/python/cpython/commit/4633f3f497b1ff70e4a35b6fe2c907cbe2d4cb2e",
            "https://github.com/python/cpython/commit/98016f7c92aa4c1232c68bac1ed6646db31782ec",
            "https://github.com/python/cpython/commit/9c1110ef6652687d7c55f590f909720eddde965a",
            "https://github.com/python/cpython/commit/9e0ac76d96cf80b49055f6d6b9a6763fb9215c2a",
            "https://github.com/python/cpython/commit/aa9eb5f757ceff461e6e996f12c89e5d9b583b01",
            "https://github.com/python/cpython/commit/dd8f187d0746da151e0025c51680979ac5b4cfb1",
            "https://github.com/python/cpython/issues/135034",
            "https://github.com/python/cpython/pull/135037",
            "https://linux.oracle.com/cve/CVE-2025-4138.html",
            "https://linux.oracle.com/errata/ELSA-2025-10189.html",
            "https://mail.python.org/archives/list/security-announce@python.org/thread/MAXIJJCUUMCL7ATZNDVEGGHUMQMUUKLG/",
            "https://nvd.nist.gov/vuln/detail/CVE-2025-4138",
            "https://ubuntu.com/security/notices/USN-7583-1",
            "https://www.cve.org/CVERecord?id=CVE-2025-4138"
          ],
          "PublishedDate": "2025-06-03T13:15:20.377Z",
          "LastModifiedDate": "2025-06-05T14:15:32.767Z"
        },
        {
          "VulnerabilityID": "CVE-2025-4517",
          "VendorIDs": [
            "RHSA-2025:10128"
          ],
          "PkgID": "platform-python@3.6.8-69.el8_10.x86_64",
          "PkgName": "platform-python",
          "PkgIdentifier": {
            "PURL": "pkg:rpm/redhat/platform-python@3.6.8-69.el8_10?arch=x86_64\u0026distro=redhat-8.10",
            "UID": "8ca2b48af17f25c6"
          },
          "InstalledVersion": "3.6.8-69.el8_10",
          "FixedVersion": "3.6.8-70.el8_10",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:2ff76d26bc63ae58824e835b041e65a91335b77fbc45c3d628f259cce07f144f"
          },
          "SeveritySource": "redhat",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2025-4517",
          "Title": "python: cpython: Arbitrary writes via tarfile realpath overflow",
          "Description": "Allows arbitrary filesystem writes outside the extraction directory during extraction with filter=\"data\".\n\n\nYou are affected by this vulnerability if using the tarfile module to extract untrusted tar archives using TarFile.extractall() or TarFile.extract() using the filter= parameter with a value of \"data\" or \"tar\". See the tarfile  extraction filters documentation https://docs.python.org/3/library/tarfile.html#tarfile-extraction-filter  for more information.\n\nNote that for Python 3.14 or later the default value of filter= changed from \"no filtering\" to `\"data\", so if you are relying on this new default behavior then your usage is also affected.\n\nNote that none of these vulnerabilities significantly affect the installation of source distributions which are tar archives as source distributions already allow arbitrary code execution during the build process. However when evaluating source distributions it's important to avoid installing source distributions with suspicious links.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-22"
          ],
          "VendorSeverity": {
            "alma": 3,
            "amazon": 3,
            "azure": 3,
            "bitnami": 4,
            "cbl-mariner": 3,
            "oracle-oval": 3,
            "photon": 4,
            "redhat": 3,
            "rocky": 3,
            "ubuntu": 2
          },
          "CVSS": {
            "bitnami": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:L",
              "V3Score": 9.4
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:H/I:H/A:L",
              "V3Score": 7.6
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2025:10189",
            "https://access.redhat.com/security/cve/CVE-2025-4517",
            "https://bugzilla.redhat.com/2370010",
            "https://bugzilla.redhat.com/2370013",
            "https://bugzilla.redhat.com/2370014",
            "https://bugzilla.redhat.com/2370016",
            "https://bugzilla.redhat.com/2372426",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370010",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370013",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370014",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370016",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2372426",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-12718",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4138",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4330",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4435",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4517",
            "https://errata.almalinux.org/9/ALSA-2025-10189.html",
            "https://errata.rockylinux.org/RLSA-2025:10031",
            "https://gist.github.com/sethmlarson/52398e33eff261329a0180ac1d54f42f",
            "https://github.com/python/cpython/commit/19de092debb3d7e832e5672cc2f7b788d35951da",
            "https://github.com/python/cpython/commit/28463dba112af719df1e8b0391c46787ad756dd9",
            "https://github.com/python/cpython/commit/3612d8f51741b11f36f8fb0494d79086bac9390a",
            "https://github.com/python/cpython/commit/4633f3f497b1ff70e4a35b6fe2c907cbe2d4cb2e",
            "https://github.com/python/cpython/commit/98016f7c92aa4c1232c68bac1ed6646db31782ec",
            "https://github.com/python/cpython/commit/9c1110ef6652687d7c55f590f909720eddde965a",
            "https://github.com/python/cpython/commit/9e0ac76d96cf80b49055f6d6b9a6763fb9215c2a",
            "https://github.com/python/cpython/commit/aa9eb5f757ceff461e6e996f12c89e5d9b583b01",
            "https://github.com/python/cpython/commit/dd8f187d0746da151e0025c51680979ac5b4cfb1",
            "https://github.com/python/cpython/issues/135034",
            "https://github.com/python/cpython/pull/135037",
            "https://linux.oracle.com/cve/CVE-2025-4517.html",
            "https://linux.oracle.com/errata/ELSA-2025-10189.html",
            "https://mail.python.org/archives/list/security-announce@python.org/thread/MAXIJJCUUMCL7ATZNDVEGGHUMQMUUKLG/",
            "https://nvd.nist.gov/vuln/detail/CVE-2025-4517",
            "https://ubuntu.com/security/notices/USN-7583-1",
            "https://www.cve.org/CVERecord?id=CVE-2025-4517"
          ],
          "PublishedDate": "2025-06-03T13:15:20.837Z",
          "LastModifiedDate": "2025-06-05T14:15:33.05Z"
        },
        {
          "VulnerabilityID": "CVE-2024-12718",
          "VendorIDs": [
            "RHSA-2025:10128"
          ],
          "PkgID": "python3-libs@3.6.8-69.el8_10.x86_64",
          "PkgName": "python3-libs",
          "PkgIdentifier": {
            "PURL": "pkg:rpm/redhat/python3-libs@3.6.8-69.el8_10?arch=x86_64\u0026distro=redhat-8.10",
            "UID": "db65ff694500b532"
          },
          "InstalledVersion": "3.6.8-69.el8_10",
          "FixedVersion": "3.6.8-70.el8_10",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:2ff76d26bc63ae58824e835b041e65a91335b77fbc45c3d628f259cce07f144f"
          },
          "SeveritySource": "redhat",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-12718",
          "Title": "cpython: python: Bypass extraction filter to modify file metadata outside extraction directory",
          "Description": "Allows modifying some file metadata (e.g. last modified) with filter=\"data\" or file permissions (chmod) with filter=\"tar\" of files outside the extraction directory.\nYou are affected by this vulnerability if using the tarfile module to extract untrusted tar archives using TarFile.extractall() or TarFile.extract() using the filter= parameter with a value of \"data\" or \"tar\". See the tarfile  extraction filters documentation https://docs.python.org/3/library/tarfile.html#tarfile-extraction-filter  for more information. Only Python versions 3.12 or later are affected by these vulnerabilities, earlier versions don't include the extraction filter feature.\n\nNote that for Python 3.14 or later the default value of filter= changed from \"no filtering\" to `\"data\", so if you are relying on this new default behavior then your usage is also affected.\n\nNote that none of these vulnerabilities significantly affect the installation of source distributions which are tar archives as source distributions already allow arbitrary code execution during the build process. However when evaluating source distributions it's important to avoid installing source distributions with suspicious links.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-22"
          ],
          "VendorSeverity": {
            "alma": 3,
            "amazon": 3,
            "bitnami": 2,
            "cbl-mariner": 2,
            "oracle-oval": 3,
            "photon": 2,
            "redhat": 3,
            "rocky": 3,
            "ubuntu": 2
          },
          "CVSS": {
            "bitnami": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
              "V3Score": 5.3
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:H/I:H/A:L",
              "V3Score": 7.6
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2025:10189",
            "https://access.redhat.com/security/cve/CVE-2024-12718",
            "https://bugzilla.redhat.com/2370010",
            "https://bugzilla.redhat.com/2370013",
            "https://bugzilla.redhat.com/2370014",
            "https://bugzilla.redhat.com/2370016",
            "https://bugzilla.redhat.com/2372426",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370010",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370013",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370014",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370016",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2372426",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-12718",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4138",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4330",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4435",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4517",
            "https://errata.almalinux.org/9/ALSA-2025-10189.html",
            "https://errata.rockylinux.org/RLSA-2025:10031",
            "https://gist.github.com/sethmlarson/52398e33eff261329a0180ac1d54f42f",
            "https://github.com/python/cpython/commit/19de092debb3d7e832e5672cc2f7b788d35951da",
            "https://github.com/python/cpython/commit/28463dba112af719df1e8b0391c46787ad756dd9",
            "https://github.com/python/cpython/commit/3612d8f51741b11f36f8fb0494d79086bac9390a",
            "https://github.com/python/cpython/commit/4633f3f497b1ff70e4a35b6fe2c907cbe2d4cb2e",
            "https://github.com/python/cpython/commit/98016f7c92aa4c1232c68bac1ed6646db31782ec",
            "https://github.com/python/cpython/commit/9c1110ef6652687d7c55f590f909720eddde965a",
            "https://github.com/python/cpython/commit/9e0ac76d96cf80b49055f6d6b9a6763fb9215c2a",
            "https://github.com/python/cpython/commit/aa9eb5f757ceff461e6e996f12c89e5d9b583b01",
            "https://github.com/python/cpython/commit/dd8f187d0746da151e0025c51680979ac5b4cfb1",
            "https://github.com/python/cpython/issues/127987",
            "https://github.com/python/cpython/issues/135034",
            "https://github.com/python/cpython/pull/135037",
            "https://linux.oracle.com/cve/CVE-2024-12718.html",
            "https://linux.oracle.com/errata/ELSA-2025-10189.html",
            "https://mail.python.org/archives/list/security-announce@python.org/thread/MAXIJJCUUMCL7ATZNDVEGGHUMQMUUKLG/",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-12718",
            "https://ubuntu.com/security/notices/USN-7583-1",
            "https://www.cve.org/CVERecord?id=CVE-2024-12718"
          ],
          "PublishedDate": "2025-06-03T13:15:20.183Z",
          "LastModifiedDate": "2025-07-24T16:15:29.157Z"
        },
        {
          "VulnerabilityID": "CVE-2025-4138",
          "VendorIDs": [
            "RHSA-2025:10128"
          ],
          "PkgID": "python3-libs@3.6.8-69.el8_10.x86_64",
          "PkgName": "python3-libs",
          "PkgIdentifier": {
            "PURL": "pkg:rpm/redhat/python3-libs@3.6.8-69.el8_10?arch=x86_64\u0026distro=redhat-8.10",
            "UID": "db65ff694500b532"
          },
          "InstalledVersion": "3.6.8-69.el8_10",
          "FixedVersion": "3.6.8-70.el8_10",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:2ff76d26bc63ae58824e835b041e65a91335b77fbc45c3d628f259cce07f144f"
          },
          "SeveritySource": "redhat",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2025-4138",
          "Title": "cpython: python: Bypassing extraction filter to create symlinks to arbitrary targets outside extraction directory",
          "Description": "Allows the extraction filter to be ignored, allowing symlink targets to point outside the destination directory, and the modification of some file metadata.\n\n\nYou are affected by this vulnerability if using the tarfile module to extract untrusted tar archives using TarFile.extractall() or TarFile.extract() using the filter= parameter with a value of \"data\" or \"tar\". See the tarfile  extraction filters documentation https://docs.python.org/3/library/tarfile.html#tarfile-extraction-filter  for more information.\n\nNote that for Python 3.14 or later the default value of filter= changed from \"no filtering\" to `\"data\", so if you are relying on this new default behavior then your usage is also affected.\n\nNote that none of these vulnerabilities significantly affect the installation of source distributions which are tar archives as source distributions already allow arbitrary code execution during the build process. However when evaluating source distributions it's important to avoid installing source distributions with suspicious links.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-22"
          ],
          "VendorSeverity": {
            "alma": 3,
            "amazon": 3,
            "bitnami": 3,
            "cbl-mariner": 3,
            "oracle-oval": 3,
            "photon": 3,
            "redhat": 3,
            "rocky": 3,
            "ubuntu": 2
          },
          "CVSS": {
            "bitnami": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
              "V3Score": 7.5
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2025:10189",
            "https://access.redhat.com/security/cve/CVE-2025-4138",
            "https://bugzilla.redhat.com/2370010",
            "https://bugzilla.redhat.com/2370013",
            "https://bugzilla.redhat.com/2370014",
            "https://bugzilla.redhat.com/2370016",
            "https://bugzilla.redhat.com/2372426",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370010",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370013",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370014",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370016",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2372426",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-12718",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4138",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4330",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4435",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4517",
            "https://errata.almalinux.org/9/ALSA-2025-10189.html",
            "https://errata.rockylinux.org/RLSA-2025:10031",
            "https://gist.github.com/sethmlarson/52398e33eff261329a0180ac1d54f42f",
            "https://github.com/python/cpython/commit/19de092debb3d7e832e5672cc2f7b788d35951da",
            "https://github.com/python/cpython/commit/28463dba112af719df1e8b0391c46787ad756dd9",
            "https://github.com/python/cpython/commit/3612d8f51741b11f36f8fb0494d79086bac9390a",
            "https://github.com/python/cpython/commit/4633f3f497b1ff70e4a35b6fe2c907cbe2d4cb2e",
            "https://github.com/python/cpython/commit/98016f7c92aa4c1232c68bac1ed6646db31782ec",
            "https://github.com/python/cpython/commit/9c1110ef6652687d7c55f590f909720eddde965a",
            "https://github.com/python/cpython/commit/9e0ac76d96cf80b49055f6d6b9a6763fb9215c2a",
            "https://github.com/python/cpython/commit/aa9eb5f757ceff461e6e996f12c89e5d9b583b01",
            "https://github.com/python/cpython/commit/dd8f187d0746da151e0025c51680979ac5b4cfb1",
            "https://github.com/python/cpython/issues/135034",
            "https://github.com/python/cpython/pull/135037",
            "https://linux.oracle.com/cve/CVE-2025-4138.html",
            "https://linux.oracle.com/errata/ELSA-2025-10189.html",
            "https://mail.python.org/archives/list/security-announce@python.org/thread/MAXIJJCUUMCL7ATZNDVEGGHUMQMUUKLG/",
            "https://nvd.nist.gov/vuln/detail/CVE-2025-4138",
            "https://ubuntu.com/security/notices/USN-7583-1",
            "https://www.cve.org/CVERecord?id=CVE-2025-4138"
          ],
          "PublishedDate": "2025-06-03T13:15:20.377Z",
          "LastModifiedDate": "2025-06-05T14:15:32.767Z"
        },
        {
          "VulnerabilityID": "CVE-2025-4517",
          "VendorIDs": [
            "RHSA-2025:10128"
          ],
          "PkgID": "python3-libs@3.6.8-69.el8_10.x86_64",
          "PkgName": "python3-libs",
          "PkgIdentifier": {
            "PURL": "pkg:rpm/redhat/python3-libs@3.6.8-69.el8_10?arch=x86_64\u0026distro=redhat-8.10",
            "UID": "db65ff694500b532"
          },
          "InstalledVersion": "3.6.8-69.el8_10",
          "FixedVersion": "3.6.8-70.el8_10",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:2ff76d26bc63ae58824e835b041e65a91335b77fbc45c3d628f259cce07f144f"
          },
          "SeveritySource": "redhat",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2025-4517",
          "Title": "python: cpython: Arbitrary writes via tarfile realpath overflow",
          "Description": "Allows arbitrary filesystem writes outside the extraction directory during extraction with filter=\"data\".\n\n\nYou are affected by this vulnerability if using the tarfile module to extract untrusted tar archives using TarFile.extractall() or TarFile.extract() using the filter= parameter with a value of \"data\" or \"tar\". See the tarfile  extraction filters documentation https://docs.python.org/3/library/tarfile.html#tarfile-extraction-filter  for more information.\n\nNote that for Python 3.14 or later the default value of filter= changed from \"no filtering\" to `\"data\", so if you are relying on this new default behavior then your usage is also affected.\n\nNote that none of these vulnerabilities significantly affect the installation of source distributions which are tar archives as source distributions already allow arbitrary code execution during the build process. However when evaluating source distributions it's important to avoid installing source distributions with suspicious links.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-22"
          ],
          "VendorSeverity": {
            "alma": 3,
            "amazon": 3,
            "azure": 3,
            "bitnami": 4,
            "cbl-mariner": 3,
            "oracle-oval": 3,
            "photon": 4,
            "redhat": 3,
            "rocky": 3,
            "ubuntu": 2
          },
          "CVSS": {
            "bitnami": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:L",
              "V3Score": 9.4
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:H/I:H/A:L",
              "V3Score": 7.6
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2025:10189",
            "https://access.redhat.com/security/cve/CVE-2025-4517",
            "https://bugzilla.redhat.com/2370010",
            "https://bugzilla.redhat.com/2370013",
            "https://bugzilla.redhat.com/2370014",
            "https://bugzilla.redhat.com/2370016",
            "https://bugzilla.redhat.com/2372426",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370010",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370013",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370014",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370016",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2372426",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-12718",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4138",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4330",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4435",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4517",
            "https://errata.almalinux.org/9/ALSA-2025-10189.html",
            "https://errata.rockylinux.org/RLSA-2025:10031",
            "https://gist.github.com/sethmlarson/52398e33eff261329a0180ac1d54f42f",
            "https://github.com/python/cpython/commit/19de092debb3d7e832e5672cc2f7b788d35951da",
            "https://github.com/python/cpython/commit/28463dba112af719df1e8b0391c46787ad756dd9",
            "https://github.com/python/cpython/commit/3612d8f51741b11f36f8fb0494d79086bac9390a",
            "https://github.com/python/cpython/commit/4633f3f497b1ff70e4a35b6fe2c907cbe2d4cb2e",
            "https://github.com/python/cpython/commit/98016f7c92aa4c1232c68bac1ed6646db31782ec",
            "https://github.com/python/cpython/commit/9c1110ef6652687d7c55f590f909720eddde965a",
            "https://github.com/python/cpython/commit/9e0ac76d96cf80b49055f6d6b9a6763fb9215c2a",
            "https://github.com/python/cpython/commit/aa9eb5f757ceff461e6e996f12c89e5d9b583b01",
            "https://github.com/python/cpython/commit/dd8f187d0746da151e0025c51680979ac5b4cfb1",
            "https://github.com/python/cpython/issues/135034",
            "https://github.com/python/cpython/pull/135037",
            "https://linux.oracle.com/cve/CVE-2025-4517.html",
            "https://linux.oracle.com/errata/ELSA-2025-10189.html",
            "https://mail.python.org/archives/list/security-announce@python.org/thread/MAXIJJCUUMCL7ATZNDVEGGHUMQMUUKLG/",
            "https://nvd.nist.gov/vuln/detail/CVE-2025-4517",
            "https://ubuntu.com/security/notices/USN-7583-1",
            "https://www.cve.org/CVERecord?id=CVE-2025-4517"
          ],
          "PublishedDate": "2025-06-03T13:15:20.837Z",
          "LastModifiedDate": "2025-06-05T14:15:33.05Z"
        },
        {
          "VulnerabilityID": "CVE-2024-12718",
          "VendorIDs": [
            "RHSA-2025:10031"
          ],
          "PkgID": "python3.12@3.12.8-1.el8_10.x86_64",
          "PkgName": "python3.12",
          "PkgIdentifier": {
            "PURL": "pkg:rpm/redhat/python3.12@3.12.8-1.el8_10?arch=x86_64\u0026distro=redhat-8.10",
            "UID": "2f6ac39a499fa410"
          },
          "InstalledVersion": "3.12.8-1.el8_10",
          "FixedVersion": "3.12.11-1.el8_10",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:a5da4d9fbfe6e37d0324cf44a30ae8fcc039c971d88564e0bd4ea8faa3b1b355"
          },
          "SeveritySource": "redhat",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-12718",
          "Title": "cpython: python: Bypass extraction filter to modify file metadata outside extraction directory",
          "Description": "Allows modifying some file metadata (e.g. last modified) with filter=\"data\" or file permissions (chmod) with filter=\"tar\" of files outside the extraction directory.\nYou are affected by this vulnerability if using the tarfile module to extract untrusted tar archives using TarFile.extractall() or TarFile.extract() using the filter= parameter with a value of \"data\" or \"tar\". See the tarfile  extraction filters documentation https://docs.python.org/3/library/tarfile.html#tarfile-extraction-filter  for more information. Only Python versions 3.12 or later are affected by these vulnerabilities, earlier versions don't include the extraction filter feature.\n\nNote that for Python 3.14 or later the default value of filter= changed from \"no filtering\" to `\"data\", so if you are relying on this new default behavior then your usage is also affected.\n\nNote that none of these vulnerabilities significantly affect the installation of source distributions which are tar archives as source distributions already allow arbitrary code execution during the build process. However when evaluating source distributions it's important to avoid installing source distributions with suspicious links.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-22"
          ],
          "VendorSeverity": {
            "alma": 3,
            "amazon": 3,
            "bitnami": 2,
            "cbl-mariner": 2,
            "oracle-oval": 3,
            "photon": 2,
            "redhat": 3,
            "rocky": 3,
            "ubuntu": 2
          },
          "CVSS": {
            "bitnami": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
              "V3Score": 5.3
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:H/I:H/A:L",
              "V3Score": 7.6
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2025:10189",
            "https://access.redhat.com/security/cve/CVE-2024-12718",
            "https://bugzilla.redhat.com/2370010",
            "https://bugzilla.redhat.com/2370013",
            "https://bugzilla.redhat.com/2370014",
            "https://bugzilla.redhat.com/2370016",
            "https://bugzilla.redhat.com/2372426",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370010",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370013",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370014",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370016",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2372426",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-12718",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4138",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4330",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4435",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4517",
            "https://errata.almalinux.org/9/ALSA-2025-10189.html",
            "https://errata.rockylinux.org/RLSA-2025:10031",
            "https://gist.github.com/sethmlarson/52398e33eff261329a0180ac1d54f42f",
            "https://github.com/python/cpython/commit/19de092debb3d7e832e5672cc2f7b788d35951da",
            "https://github.com/python/cpython/commit/28463dba112af719df1e8b0391c46787ad756dd9",
            "https://github.com/python/cpython/commit/3612d8f51741b11f36f8fb0494d79086bac9390a",
            "https://github.com/python/cpython/commit/4633f3f497b1ff70e4a35b6fe2c907cbe2d4cb2e",
            "https://github.com/python/cpython/commit/98016f7c92aa4c1232c68bac1ed6646db31782ec",
            "https://github.com/python/cpython/commit/9c1110ef6652687d7c55f590f909720eddde965a",
            "https://github.com/python/cpython/commit/9e0ac76d96cf80b49055f6d6b9a6763fb9215c2a",
            "https://github.com/python/cpython/commit/aa9eb5f757ceff461e6e996f12c89e5d9b583b01",
            "https://github.com/python/cpython/commit/dd8f187d0746da151e0025c51680979ac5b4cfb1",
            "https://github.com/python/cpython/issues/127987",
            "https://github.com/python/cpython/issues/135034",
            "https://github.com/python/cpython/pull/135037",
            "https://linux.oracle.com/cve/CVE-2024-12718.html",
            "https://linux.oracle.com/errata/ELSA-2025-10189.html",
            "https://mail.python.org/archives/list/security-announce@python.org/thread/MAXIJJCUUMCL7ATZNDVEGGHUMQMUUKLG/",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-12718",
            "https://ubuntu.com/security/notices/USN-7583-1",
            "https://www.cve.org/CVERecord?id=CVE-2024-12718"
          ],
          "PublishedDate": "2025-06-03T13:15:20.183Z",
          "LastModifiedDate": "2025-07-24T16:15:29.157Z"
        },
        {
          "VulnerabilityID": "CVE-2025-4138",
          "VendorIDs": [
            "RHSA-2025:10031"
          ],
          "PkgID": "python3.12@3.12.8-1.el8_10.x86_64",
          "PkgName": "python3.12",
          "PkgIdentifier": {
            "PURL": "pkg:rpm/redhat/python3.12@3.12.8-1.el8_10?arch=x86_64\u0026distro=redhat-8.10",
            "UID": "2f6ac39a499fa410"
          },
          "InstalledVersion": "3.12.8-1.el8_10",
          "FixedVersion": "3.12.11-1.el8_10",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:a5da4d9fbfe6e37d0324cf44a30ae8fcc039c971d88564e0bd4ea8faa3b1b355"
          },
          "SeveritySource": "redhat",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2025-4138",
          "Title": "cpython: python: Bypassing extraction filter to create symlinks to arbitrary targets outside extraction directory",
          "Description": "Allows the extraction filter to be ignored, allowing symlink targets to point outside the destination directory, and the modification of some file metadata.\n\n\nYou are affected by this vulnerability if using the tarfile module to extract untrusted tar archives using TarFile.extractall() or TarFile.extract() using the filter= parameter with a value of \"data\" or \"tar\". See the tarfile  extraction filters documentation https://docs.python.org/3/library/tarfile.html#tarfile-extraction-filter  for more information.\n\nNote that for Python 3.14 or later the default value of filter= changed from \"no filtering\" to `\"data\", so if you are relying on this new default behavior then your usage is also affected.\n\nNote that none of these vulnerabilities significantly affect the installation of source distributions which are tar archives as source distributions already allow arbitrary code execution during the build process. However when evaluating source distributions it's important to avoid installing source distributions with suspicious links.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-22"
          ],
          "VendorSeverity": {
            "alma": 3,
            "amazon": 3,
            "bitnami": 3,
            "cbl-mariner": 3,
            "oracle-oval": 3,
            "photon": 3,
            "redhat": 3,
            "rocky": 3,
            "ubuntu": 2
          },
          "CVSS": {
            "bitnami": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
              "V3Score": 7.5
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2025:10189",
            "https://access.redhat.com/security/cve/CVE-2025-4138",
            "https://bugzilla.redhat.com/2370010",
            "https://bugzilla.redhat.com/2370013",
            "https://bugzilla.redhat.com/2370014",
            "https://bugzilla.redhat.com/2370016",
            "https://bugzilla.redhat.com/2372426",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370010",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370013",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370014",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370016",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2372426",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-12718",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4138",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4330",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4435",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4517",
            "https://errata.almalinux.org/9/ALSA-2025-10189.html",
            "https://errata.rockylinux.org/RLSA-2025:10031",
            "https://gist.github.com/sethmlarson/52398e33eff261329a0180ac1d54f42f",
            "https://github.com/python/cpython/commit/19de092debb3d7e832e5672cc2f7b788d35951da",
            "https://github.com/python/cpython/commit/28463dba112af719df1e8b0391c46787ad756dd9",
            "https://github.com/python/cpython/commit/3612d8f51741b11f36f8fb0494d79086bac9390a",
            "https://github.com/python/cpython/commit/4633f3f497b1ff70e4a35b6fe2c907cbe2d4cb2e",
            "https://github.com/python/cpython/commit/98016f7c92aa4c1232c68bac1ed6646db31782ec",
            "https://github.com/python/cpython/commit/9c1110ef6652687d7c55f590f909720eddde965a",
            "https://github.com/python/cpython/commit/9e0ac76d96cf80b49055f6d6b9a6763fb9215c2a",
            "https://github.com/python/cpython/commit/aa9eb5f757ceff461e6e996f12c89e5d9b583b01",
            "https://github.com/python/cpython/commit/dd8f187d0746da151e0025c51680979ac5b4cfb1",
            "https://github.com/python/cpython/issues/135034",
            "https://github.com/python/cpython/pull/135037",
            "https://linux.oracle.com/cve/CVE-2025-4138.html",
            "https://linux.oracle.com/errata/ELSA-2025-10189.html",
            "https://mail.python.org/archives/list/security-announce@python.org/thread/MAXIJJCUUMCL7ATZNDVEGGHUMQMUUKLG/",
            "https://nvd.nist.gov/vuln/detail/CVE-2025-4138",
            "https://ubuntu.com/security/notices/USN-7583-1",
            "https://www.cve.org/CVERecord?id=CVE-2025-4138"
          ],
          "PublishedDate": "2025-06-03T13:15:20.377Z",
          "LastModifiedDate": "2025-06-05T14:15:32.767Z"
        },
        {
          "VulnerabilityID": "CVE-2025-4517",
          "VendorIDs": [
            "RHSA-2025:10031"
          ],
          "PkgID": "python3.12@3.12.8-1.el8_10.x86_64",
          "PkgName": "python3.12",
          "PkgIdentifier": {
            "PURL": "pkg:rpm/redhat/python3.12@3.12.8-1.el8_10?arch=x86_64\u0026distro=redhat-8.10",
            "UID": "2f6ac39a499fa410"
          },
          "InstalledVersion": "3.12.8-1.el8_10",
          "FixedVersion": "3.12.11-1.el8_10",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:a5da4d9fbfe6e37d0324cf44a30ae8fcc039c971d88564e0bd4ea8faa3b1b355"
          },
          "SeveritySource": "redhat",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2025-4517",
          "Title": "python: cpython: Arbitrary writes via tarfile realpath overflow",
          "Description": "Allows arbitrary filesystem writes outside the extraction directory during extraction with filter=\"data\".\n\n\nYou are affected by this vulnerability if using the tarfile module to extract untrusted tar archives using TarFile.extractall() or TarFile.extract() using the filter= parameter with a value of \"data\" or \"tar\". See the tarfile  extraction filters documentation https://docs.python.org/3/library/tarfile.html#tarfile-extraction-filter  for more information.\n\nNote that for Python 3.14 or later the default value of filter= changed from \"no filtering\" to `\"data\", so if you are relying on this new default behavior then your usage is also affected.\n\nNote that none of these vulnerabilities significantly affect the installation of source distributions which are tar archives as source distributions already allow arbitrary code execution during the build process. However when evaluating source distributions it's important to avoid installing source distributions with suspicious links.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-22"
          ],
          "VendorSeverity": {
            "alma": 3,
            "amazon": 3,
            "azure": 3,
            "bitnami": 4,
            "cbl-mariner": 3,
            "oracle-oval": 3,
            "photon": 4,
            "redhat": 3,
            "rocky": 3,
            "ubuntu": 2
          },
          "CVSS": {
            "bitnami": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:L",
              "V3Score": 9.4
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:H/I:H/A:L",
              "V3Score": 7.6
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2025:10189",
            "https://access.redhat.com/security/cve/CVE-2025-4517",
            "https://bugzilla.redhat.com/2370010",
            "https://bugzilla.redhat.com/2370013",
            "https://bugzilla.redhat.com/2370014",
            "https://bugzilla.redhat.com/2370016",
            "https://bugzilla.redhat.com/2372426",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370010",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370013",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370014",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370016",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2372426",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-12718",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4138",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4330",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4435",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4517",
            "https://errata.almalinux.org/9/ALSA-2025-10189.html",
            "https://errata.rockylinux.org/RLSA-2025:10031",
            "https://gist.github.com/sethmlarson/52398e33eff261329a0180ac1d54f42f",
            "https://github.com/python/cpython/commit/19de092debb3d7e832e5672cc2f7b788d35951da",
            "https://github.com/python/cpython/commit/28463dba112af719df1e8b0391c46787ad756dd9",
            "https://github.com/python/cpython/commit/3612d8f51741b11f36f8fb0494d79086bac9390a",
            "https://github.com/python/cpython/commit/4633f3f497b1ff70e4a35b6fe2c907cbe2d4cb2e",
            "https://github.com/python/cpython/commit/98016f7c92aa4c1232c68bac1ed6646db31782ec",
            "https://github.com/python/cpython/commit/9c1110ef6652687d7c55f590f909720eddde965a",
            "https://github.com/python/cpython/commit/9e0ac76d96cf80b49055f6d6b9a6763fb9215c2a",
            "https://github.com/python/cpython/commit/aa9eb5f757ceff461e6e996f12c89e5d9b583b01",
            "https://github.com/python/cpython/commit/dd8f187d0746da151e0025c51680979ac5b4cfb1",
            "https://github.com/python/cpython/issues/135034",
            "https://github.com/python/cpython/pull/135037",
            "https://linux.oracle.com/cve/CVE-2025-4517.html",
            "https://linux.oracle.com/errata/ELSA-2025-10189.html",
            "https://mail.python.org/archives/list/security-announce@python.org/thread/MAXIJJCUUMCL7ATZNDVEGGHUMQMUUKLG/",
            "https://nvd.nist.gov/vuln/detail/CVE-2025-4517",
            "https://ubuntu.com/security/notices/USN-7583-1",
            "https://www.cve.org/CVERecord?id=CVE-2025-4517"
          ],
          "PublishedDate": "2025-06-03T13:15:20.837Z",
          "LastModifiedDate": "2025-06-05T14:15:33.05Z"
        },
        {
          "VulnerabilityID": "CVE-2024-12718",
          "VendorIDs": [
            "RHSA-2025:10031"
          ],
          "PkgID": "python3.12-libs@3.12.8-1.el8_10.x86_64",
          "PkgName": "python3.12-libs",
          "PkgIdentifier": {
            "PURL": "pkg:rpm/redhat/python3.12-libs@3.12.8-1.el8_10?arch=x86_64\u0026distro=redhat-8.10",
            "UID": "9ac9f59e4f8ca4ee"
          },
          "InstalledVersion": "3.12.8-1.el8_10",
          "FixedVersion": "3.12.11-1.el8_10",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:a5da4d9fbfe6e37d0324cf44a30ae8fcc039c971d88564e0bd4ea8faa3b1b355"
          },
          "SeveritySource": "redhat",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-12718",
          "Title": "cpython: python: Bypass extraction filter to modify file metadata outside extraction directory",
          "Description": "Allows modifying some file metadata (e.g. last modified) with filter=\"data\" or file permissions (chmod) with filter=\"tar\" of files outside the extraction directory.\nYou are affected by this vulnerability if using the tarfile module to extract untrusted tar archives using TarFile.extractall() or TarFile.extract() using the filter= parameter with a value of \"data\" or \"tar\". See the tarfile  extraction filters documentation https://docs.python.org/3/library/tarfile.html#tarfile-extraction-filter  for more information. Only Python versions 3.12 or later are affected by these vulnerabilities, earlier versions don't include the extraction filter feature.\n\nNote that for Python 3.14 or later the default value of filter= changed from \"no filtering\" to `\"data\", so if you are relying on this new default behavior then your usage is also affected.\n\nNote that none of these vulnerabilities significantly affect the installation of source distributions which are tar archives as source distributions already allow arbitrary code execution during the build process. However when evaluating source distributions it's important to avoid installing source distributions with suspicious links.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-22"
          ],
          "VendorSeverity": {
            "alma": 3,
            "amazon": 3,
            "bitnami": 2,
            "cbl-mariner": 2,
            "oracle-oval": 3,
            "photon": 2,
            "redhat": 3,
            "rocky": 3,
            "ubuntu": 2
          },
          "CVSS": {
            "bitnami": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
              "V3Score": 5.3
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:H/I:H/A:L",
              "V3Score": 7.6
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2025:10189",
            "https://access.redhat.com/security/cve/CVE-2024-12718",
            "https://bugzilla.redhat.com/2370010",
            "https://bugzilla.redhat.com/2370013",
            "https://bugzilla.redhat.com/2370014",
            "https://bugzilla.redhat.com/2370016",
            "https://bugzilla.redhat.com/2372426",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370010",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370013",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370014",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370016",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2372426",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-12718",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4138",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4330",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4435",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4517",
            "https://errata.almalinux.org/9/ALSA-2025-10189.html",
            "https://errata.rockylinux.org/RLSA-2025:10031",
            "https://gist.github.com/sethmlarson/52398e33eff261329a0180ac1d54f42f",
            "https://github.com/python/cpython/commit/19de092debb3d7e832e5672cc2f7b788d35951da",
            "https://github.com/python/cpython/commit/28463dba112af719df1e8b0391c46787ad756dd9",
            "https://github.com/python/cpython/commit/3612d8f51741b11f36f8fb0494d79086bac9390a",
            "https://github.com/python/cpython/commit/4633f3f497b1ff70e4a35b6fe2c907cbe2d4cb2e",
            "https://github.com/python/cpython/commit/98016f7c92aa4c1232c68bac1ed6646db31782ec",
            "https://github.com/python/cpython/commit/9c1110ef6652687d7c55f590f909720eddde965a",
            "https://github.com/python/cpython/commit/9e0ac76d96cf80b49055f6d6b9a6763fb9215c2a",
            "https://github.com/python/cpython/commit/aa9eb5f757ceff461e6e996f12c89e5d9b583b01",
            "https://github.com/python/cpython/commit/dd8f187d0746da151e0025c51680979ac5b4cfb1",
            "https://github.com/python/cpython/issues/127987",
            "https://github.com/python/cpython/issues/135034",
            "https://github.com/python/cpython/pull/135037",
            "https://linux.oracle.com/cve/CVE-2024-12718.html",
            "https://linux.oracle.com/errata/ELSA-2025-10189.html",
            "https://mail.python.org/archives/list/security-announce@python.org/thread/MAXIJJCUUMCL7ATZNDVEGGHUMQMUUKLG/",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-12718",
            "https://ubuntu.com/security/notices/USN-7583-1",
            "https://www.cve.org/CVERecord?id=CVE-2024-12718"
          ],
          "PublishedDate": "2025-06-03T13:15:20.183Z",
          "LastModifiedDate": "2025-07-24T16:15:29.157Z"
        },
        {
          "VulnerabilityID": "CVE-2025-4138",
          "VendorIDs": [
            "RHSA-2025:10031"
          ],
          "PkgID": "python3.12-libs@3.12.8-1.el8_10.x86_64",
          "PkgName": "python3.12-libs",
          "PkgIdentifier": {
            "PURL": "pkg:rpm/redhat/python3.12-libs@3.12.8-1.el8_10?arch=x86_64\u0026distro=redhat-8.10",
            "UID": "9ac9f59e4f8ca4ee"
          },
          "InstalledVersion": "3.12.8-1.el8_10",
          "FixedVersion": "3.12.11-1.el8_10",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:a5da4d9fbfe6e37d0324cf44a30ae8fcc039c971d88564e0bd4ea8faa3b1b355"
          },
          "SeveritySource": "redhat",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2025-4138",
          "Title": "cpython: python: Bypassing extraction filter to create symlinks to arbitrary targets outside extraction directory",
          "Description": "Allows the extraction filter to be ignored, allowing symlink targets to point outside the destination directory, and the modification of some file metadata.\n\n\nYou are affected by this vulnerability if using the tarfile module to extract untrusted tar archives using TarFile.extractall() or TarFile.extract() using the filter= parameter with a value of \"data\" or \"tar\". See the tarfile  extraction filters documentation https://docs.python.org/3/library/tarfile.html#tarfile-extraction-filter  for more information.\n\nNote that for Python 3.14 or later the default value of filter= changed from \"no filtering\" to `\"data\", so if you are relying on this new default behavior then your usage is also affected.\n\nNote that none of these vulnerabilities significantly affect the installation of source distributions which are tar archives as source distributions already allow arbitrary code execution during the build process. However when evaluating source distributions it's important to avoid installing source distributions with suspicious links.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-22"
          ],
          "VendorSeverity": {
            "alma": 3,
            "amazon": 3,
            "bitnami": 3,
            "cbl-mariner": 3,
            "oracle-oval": 3,
            "photon": 3,
            "redhat": 3,
            "rocky": 3,
            "ubuntu": 2
          },
          "CVSS": {
            "bitnami": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
              "V3Score": 7.5
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2025:10189",
            "https://access.redhat.com/security/cve/CVE-2025-4138",
            "https://bugzilla.redhat.com/2370010",
            "https://bugzilla.redhat.com/2370013",
            "https://bugzilla.redhat.com/2370014",
            "https://bugzilla.redhat.com/2370016",
            "https://bugzilla.redhat.com/2372426",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370010",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370013",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370014",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370016",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2372426",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-12718",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4138",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4330",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4435",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4517",
            "https://errata.almalinux.org/9/ALSA-2025-10189.html",
            "https://errata.rockylinux.org/RLSA-2025:10031",
            "https://gist.github.com/sethmlarson/52398e33eff261329a0180ac1d54f42f",
            "https://github.com/python/cpython/commit/19de092debb3d7e832e5672cc2f7b788d35951da",
            "https://github.com/python/cpython/commit/28463dba112af719df1e8b0391c46787ad756dd9",
            "https://github.com/python/cpython/commit/3612d8f51741b11f36f8fb0494d79086bac9390a",
            "https://github.com/python/cpython/commit/4633f3f497b1ff70e4a35b6fe2c907cbe2d4cb2e",
            "https://github.com/python/cpython/commit/98016f7c92aa4c1232c68bac1ed6646db31782ec",
            "https://github.com/python/cpython/commit/9c1110ef6652687d7c55f590f909720eddde965a",
            "https://github.com/python/cpython/commit/9e0ac76d96cf80b49055f6d6b9a6763fb9215c2a",
            "https://github.com/python/cpython/commit/aa9eb5f757ceff461e6e996f12c89e5d9b583b01",
            "https://github.com/python/cpython/commit/dd8f187d0746da151e0025c51680979ac5b4cfb1",
            "https://github.com/python/cpython/issues/135034",
            "https://github.com/python/cpython/pull/135037",
            "https://linux.oracle.com/cve/CVE-2025-4138.html",
            "https://linux.oracle.com/errata/ELSA-2025-10189.html",
            "https://mail.python.org/archives/list/security-announce@python.org/thread/MAXIJJCUUMCL7ATZNDVEGGHUMQMUUKLG/",
            "https://nvd.nist.gov/vuln/detail/CVE-2025-4138",
            "https://ubuntu.com/security/notices/USN-7583-1",
            "https://www.cve.org/CVERecord?id=CVE-2025-4138"
          ],
          "PublishedDate": "2025-06-03T13:15:20.377Z",
          "LastModifiedDate": "2025-06-05T14:15:32.767Z"
        },
        {
          "VulnerabilityID": "CVE-2025-4517",
          "VendorIDs": [
            "RHSA-2025:10031"
          ],
          "PkgID": "python3.12-libs@3.12.8-1.el8_10.x86_64",
          "PkgName": "python3.12-libs",
          "PkgIdentifier": {
            "PURL": "pkg:rpm/redhat/python3.12-libs@3.12.8-1.el8_10?arch=x86_64\u0026distro=redhat-8.10",
            "UID": "9ac9f59e4f8ca4ee"
          },
          "InstalledVersion": "3.12.8-1.el8_10",
          "FixedVersion": "3.12.11-1.el8_10",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:a5da4d9fbfe6e37d0324cf44a30ae8fcc039c971d88564e0bd4ea8faa3b1b355"
          },
          "SeveritySource": "redhat",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2025-4517",
          "Title": "python: cpython: Arbitrary writes via tarfile realpath overflow",
          "Description": "Allows arbitrary filesystem writes outside the extraction directory during extraction with filter=\"data\".\n\n\nYou are affected by this vulnerability if using the tarfile module to extract untrusted tar archives using TarFile.extractall() or TarFile.extract() using the filter= parameter with a value of \"data\" or \"tar\". See the tarfile  extraction filters documentation https://docs.python.org/3/library/tarfile.html#tarfile-extraction-filter  for more information.\n\nNote that for Python 3.14 or later the default value of filter= changed from \"no filtering\" to `\"data\", so if you are relying on this new default behavior then your usage is also affected.\n\nNote that none of these vulnerabilities significantly affect the installation of source distributions which are tar archives as source distributions already allow arbitrary code execution during the build process. However when evaluating source distributions it's important to avoid installing source distributions with suspicious links.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-22"
          ],
          "VendorSeverity": {
            "alma": 3,
            "amazon": 3,
            "azure": 3,
            "bitnami": 4,
            "cbl-mariner": 3,
            "oracle-oval": 3,
            "photon": 4,
            "redhat": 3,
            "rocky": 3,
            "ubuntu": 2
          },
          "CVSS": {
            "bitnami": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:L",
              "V3Score": 9.4
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:H/I:H/A:L",
              "V3Score": 7.6
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2025:10189",
            "https://access.redhat.com/security/cve/CVE-2025-4517",
            "https://bugzilla.redhat.com/2370010",
            "https://bugzilla.redhat.com/2370013",
            "https://bugzilla.redhat.com/2370014",
            "https://bugzilla.redhat.com/2370016",
            "https://bugzilla.redhat.com/2372426",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370010",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370013",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370014",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370016",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2372426",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-12718",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4138",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4330",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4435",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4517",
            "https://errata.almalinux.org/9/ALSA-2025-10189.html",
            "https://errata.rockylinux.org/RLSA-2025:10031",
            "https://gist.github.com/sethmlarson/52398e33eff261329a0180ac1d54f42f",
            "https://github.com/python/cpython/commit/19de092debb3d7e832e5672cc2f7b788d35951da",
            "https://github.com/python/cpython/commit/28463dba112af719df1e8b0391c46787ad756dd9",
            "https://github.com/python/cpython/commit/3612d8f51741b11f36f8fb0494d79086bac9390a",
            "https://github.com/python/cpython/commit/4633f3f497b1ff70e4a35b6fe2c907cbe2d4cb2e",
            "https://github.com/python/cpython/commit/98016f7c92aa4c1232c68bac1ed6646db31782ec",
            "https://github.com/python/cpython/commit/9c1110ef6652687d7c55f590f909720eddde965a",
            "https://github.com/python/cpython/commit/9e0ac76d96cf80b49055f6d6b9a6763fb9215c2a",
            "https://github.com/python/cpython/commit/aa9eb5f757ceff461e6e996f12c89e5d9b583b01",
            "https://github.com/python/cpython/commit/dd8f187d0746da151e0025c51680979ac5b4cfb1",
            "https://github.com/python/cpython/issues/135034",
            "https://github.com/python/cpython/pull/135037",
            "https://linux.oracle.com/cve/CVE-2025-4517.html",
            "https://linux.oracle.com/errata/ELSA-2025-10189.html",
            "https://mail.python.org/archives/list/security-announce@python.org/thread/MAXIJJCUUMCL7ATZNDVEGGHUMQMUUKLG/",
            "https://nvd.nist.gov/vuln/detail/CVE-2025-4517",
            "https://ubuntu.com/security/notices/USN-7583-1",
            "https://www.cve.org/CVERecord?id=CVE-2025-4517"
          ],
          "PublishedDate": "2025-06-03T13:15:20.837Z",
          "LastModifiedDate": "2025-06-05T14:15:33.05Z"
        },
        {
          "VulnerabilityID": "CVE-2025-6965",
          "VendorIDs": [
            "RHSA-2025:12010"
          ],
          "PkgID": "sqlite-libs@3.26.0-19.el8_9.x86_64",
          "PkgName": "sqlite-libs",
          "PkgIdentifier": {
            "PURL": "pkg:rpm/redhat/sqlite-libs@3.26.0-19.el8_9?arch=x86_64\u0026distro=redhat-8.10",
            "UID": "d40c2ef54273abf4"
          },
          "InstalledVersion": "3.26.0-19.el8_9",
          "FixedVersion": "3.26.0-20.el8_10",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:2ff76d26bc63ae58824e835b041e65a91335b77fbc45c3d628f259cce07f144f"
          },
          "SeveritySource": "redhat",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2025-6965",
          "Title": "sqlite: Integer Truncation in SQLite",
          "Description": "There exists a vulnerability in SQLite versions before 3.50.2 where the number of aggregate terms could exceed the number of columns available. This could lead to a memory corruption issue. We recommend upgrading to version 3.50.2 or above.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-197"
          ],
          "VendorSeverity": {
            "alma": 3,
            "amazon": 2,
            "bitnami": 3,
            "cbl-mariner": 3,
            "nvd": 4,
            "oracle-oval": 3,
            "redhat": 3,
            "rocky": 3,
            "ubuntu": 2
          },
          "CVSS": {
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 9.8
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:C/C:L/I:H/A:L",
              "V3Score": 7.7
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2025:11992",
            "https://access.redhat.com/security/cve/CVE-2025-6965",
            "https://bugzilla.redhat.com/2380149",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2380149",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-6965",
            "https://errata.almalinux.org/9/ALSA-2025-11992.html",
            "https://errata.rockylinux.org/RLSA-2025:12010",
            "https://linux.oracle.com/cve/CVE-2025-6965.html",
            "https://linux.oracle.com/errata/ELSA-2025-12349.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2025-6965",
            "https://ubuntu.com/security/notices/USN-7676-1",
            "https://ubuntu.com/security/notices/USN-7679-1",
            "https://www.cve.org/CVERecord?id=CVE-2025-6965",
            "https://www.sqlite.org/src/info/5508b56fd24016c13981ec280ecdd833007c9d8dd595edb295b984c2b487b5c8"
          ],
          "PublishedDate": "2025-07-15T14:15:31.08Z",
          "LastModifiedDate": "2025-07-22T17:06:21.51Z"
        }
      ]
    }
  ]
}