{
  "SchemaVersion": 2,
  "CreatedAt": "2025-08-21T20:55:18.680483651Z",
  "ArtifactName": "/tmp/trivy-archive-U3FeyE/localhost_ubi8_8.10.tar",
  "ArtifactType": "container_image",
  "Metadata": {
    "OS": {
      "Family": "redhat",
      "Name": "8.10"
    },
    "ImageID": "sha256:b7cd93e154b49774a2110c33695b6c235ca6d6dfd401857c5accf47c6be21311",
    "DiffIDs": [
      "sha256:2ff76d26bc63ae58824e835b041e65a91335b77fbc45c3d628f259cce07f144f"
    ],
    "ImageConfig": {
      "architecture": "amd64",
      "created": "2025-03-13T11:34:21.806107703Z",
      "history": [
        {
          "created": "2025-03-13T11:34:15.047895819Z",
          "created_by": "/bin/sh -c #(nop) ADD file:04e3bb8dbcc173469bd087cd598892daaf55ccbfd076b7ba5de6c0242fb54cb0 in / ",
          "empty_layer": true
        },
        {
          "created": "2025-03-13T11:34:15.924305518Z",
          "created_by": "/bin/sh -c mv -f /etc/yum.repos.d/ubi.repo /tmp || :",
          "empty_layer": true
        },
        {
          "created": "2025-03-13T11:34:16.218900987Z",
          "created_by": "/bin/sh -c #(nop) ADD file:df13b6a4fdeac4626ab7cd7e99d16d30edc6e3e5441295ae7691bee26604a5b1 in /tmp/tls-ca-bundle.pem ",
          "empty_layer": true
        },
        {
          "created": "2025-03-13T11:34:16.605381313Z",
          "created_by": "/bin/sh -c #(nop) ADD multi:771be6fff9a852e557be99b0f12cda1b1c36d9bdb4af98b64a96cf7211fbeaa5 in /etc/yum.repos.d/ ",
          "empty_layer": true
        },
        {
          "created": "2025-03-13T11:34:16.605425709Z",
          "created_by": "/bin/sh -c #(nop) LABEL maintainer=\"Red Hat, Inc.\"",
          "empty_layer": true
        },
        {
          "created": "2025-03-13T11:34:16.605531267Z",
          "created_by": "/bin/sh -c #(nop) LABEL com.redhat.component=\"ubi8-container\"       name=\"ubi8\"       version=\"8.10\"",
          "empty_layer": true
        },
        {
          "created": "2025-03-13T11:34:16.605578667Z",
          "created_by": "/bin/sh -c #(nop) LABEL com.redhat.license_terms=\"https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI\"",
          "empty_layer": true
        },
        {
          "created": "2025-03-13T11:34:16.60561388Z",
          "created_by": "/bin/sh -c #(nop) LABEL summary=\"Provides the latest release of Red Hat Universal Base Image 8.\"",
          "empty_layer": true
        },
        {
          "created": "2025-03-13T11:34:16.605729203Z",
          "created_by": "/bin/sh -c #(nop) LABEL description=\"The Universal Base Image is designed and engineered to be the base layer for all of your containerized applications, middleware and utilities. This base image is freely redistributable, but Red Hat only supports Red Hat technologies through subscriptions for Red Hat products. This image is maintained by Red Hat and updated regularly.\"",
          "empty_layer": true
        },
        {
          "created": "2025-03-13T11:34:16.605770044Z",
          "created_by": "/bin/sh -c #(nop) LABEL io.k8s.display-name=\"Red Hat Universal Base Image 8\"",
          "empty_layer": true
        },
        {
          "created": "2025-03-13T11:34:16.605805138Z",
          "created_by": "/bin/sh -c #(nop) LABEL io.openshift.expose-services=\"\"",
          "empty_layer": true
        },
        {
          "created": "2025-03-13T11:34:16.605832194Z",
          "created_by": "/bin/sh -c #(nop) LABEL io.openshift.tags=\"base rhel8\"",
          "empty_layer": true
        },
        {
          "created": "2025-03-13T11:34:16.605846652Z",
          "created_by": "/bin/sh -c #(nop) ENV container oci",
          "empty_layer": true
        },
        {
          "created": "2025-03-13T11:34:16.605908993Z",
          "created_by": "/bin/sh -c #(nop) ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
          "empty_layer": true
        },
        {
          "created": "2025-03-13T11:34:16.60592357Z",
          "created_by": "/bin/sh -c #(nop) CMD [\"/bin/bash\"]",
          "empty_layer": true
        },
        {
          "created": "2025-03-13T11:34:17.422485596Z",
          "created_by": "/bin/sh -c rm -rf /var/log/*",
          "empty_layer": true
        },
        {
          "created": "2025-03-13T11:34:18.221313478Z",
          "created_by": "/bin/sh -c mkdir -p /var/log/rhsm",
          "empty_layer": true
        },
        {
          "created": "2025-03-13T11:34:18.491113876Z",
          "created_by": "/bin/sh -c #(nop) ADD file:b2504ac56e42d221cb97ae63b245e52d960e7417b4da4abdda91f820a1dd5708 in /root/buildinfo/content_manifests/ubi8-container-8.10-1184.1741863532.json ",
          "empty_layer": true
        },
        {
          "created": "2025-03-13T11:34:18.799596697Z",
          "created_by": "/bin/sh -c #(nop) ADD file:fc0e17da15a231b0a8534ffb8ef0fbf087a6da1ff35f8721112100089ce4afc5 in /root/buildinfo/Dockerfile-ubi8-8.10-1184.1741863532 ",
          "empty_layer": true
        },
        {
          "created": "2025-03-13T11:34:18.799816644Z",
          "created_by": "/bin/sh -c #(nop) LABEL \"release\"=\"1184.1741863532\" \"distribution-scope\"=\"public\" \"vendor\"=\"Red Hat, Inc.\" \"build-date\"=\"2025-03-13T10:59:43\" \"architecture\"=\"x86_64\" \"vcs-type\"=\"git\" \"vcs-ref\"=\"967861a8dbbb288b8cec9f1fee7ccbf6c7ee9a20\" \"io.k8s.description\"=\"The Universal Base Image is designed and engineered to be the base layer for all of your containerized applications, middleware and utilities. This base image is freely redistributable, but Red Hat only supports Red Hat technologies through subscriptions for Red Hat products. This image is maintained by Red Hat and updated regularly.\" \"url\"=\"https://access.redhat.com/containers/#/registry.access.redhat.com/ubi8/images/8.10-1184.1741863532\"",
          "empty_layer": true
        },
        {
          "created": "2025-03-13T11:34:19.678426013Z",
          "created_by": "/bin/sh -c rm -f '/etc/yum.repos.d/odcs-3978716-29051.repo' '/etc/yum.repos.d/rhel-8.10-compose-0e878.repo'",
          "empty_layer": true
        },
        {
          "created": "2025-03-13T11:34:20.729464853Z",
          "created_by": "/bin/sh -c rm -f /tmp/tls-ca-bundle.pem",
          "empty_layer": true
        },
        {
          "created": "2025-03-13T11:34:23.860418304Z",
          "created_by": "/bin/sh -c mv -fZ /tmp/ubi.repo /etc/yum.repos.d/ubi.repo || :"
        }
      ],
      "os": "linux",
      "rootfs": {
        "type": "layers",
        "diff_ids": [
          "sha256:2ff76d26bc63ae58824e835b041e65a91335b77fbc45c3d628f259cce07f144f"
        ]
      },
      "config": {
        "Cmd": [
          "/bin/bash"
        ],
        "Env": [
          "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
          "container=oci"
        ],
        "Labels": {
          "architecture": "x86_64",
          "build-date": "2025-03-13T10:59:43",
          "com.redhat.component": "ubi8-container",
          "com.redhat.license_terms": "https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI",
          "description": "The Universal Base Image is designed and engineered to be the base layer for all of your containerized applications, middleware and utilities. This base image is freely redistributable, but Red Hat only supports Red Hat technologies through subscriptions for Red Hat products. This image is maintained by Red Hat and updated regularly.",
          "distribution-scope": "public",
          "io.buildah.version": "1.33.12",
          "io.k8s.description": "The Universal Base Image is designed and engineered to be the base layer for all of your containerized applications, middleware and utilities. This base image is freely redistributable, but Red Hat only supports Red Hat technologies through subscriptions for Red Hat products. This image is maintained by Red Hat and updated regularly.",
          "io.k8s.display-name": "Red Hat Universal Base Image 8",
          "io.openshift.expose-services": "",
          "io.openshift.tags": "base rhel8",
          "maintainer": "Red Hat, Inc.",
          "name": "ubi8",
          "release": "1184.1741863532",
          "summary": "Provides the latest release of Red Hat Universal Base Image 8.",
          "url": "https://access.redhat.com/containers/#/registry.access.redhat.com/ubi8/images/8.10-1184.1741863532",
          "vcs-ref": "967861a8dbbb288b8cec9f1fee7ccbf6c7ee9a20",
          "vcs-type": "git",
          "vendor": "Red Hat, Inc.",
          "version": "8.10"
        }
      }
    }
  },
  "Results": [
    {
      "Target": "/tmp/trivy-archive-U3FeyE/localhost_ubi8_8.10.tar (redhat 8.10)",
      "Class": "os-pkgs",
      "Type": "redhat",
      "Vulnerabilities": [
        {
          "VulnerabilityID": "CVE-2025-5914",
          "PkgID": "libarchive@3.3.3-5.el8.x86_64",
          "PkgName": "libarchive",
          "PkgIdentifier": {
            "PURL": "pkg:rpm/redhat/libarchive@3.3.3-5.el8?arch=x86_64\u0026distro=redhat-8.10",
            "UID": "4e3475e0df18476c"
          },
          "InstalledVersion": "3.3.3-5.el8",
          "Status": "affected",
          "Layer": {
            "DiffID": "sha256:2ff76d26bc63ae58824e835b041e65a91335b77fbc45c3d628f259cce07f144f"
          },
          "SeveritySource": "redhat",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2025-5914",
          "Title": "libarchive: Double free at archive_read_format_rar_seek_data() in archive_read_support_format_rar.c",
          "Description": "A vulnerability has been identified in the libarchive library, specifically within the archive_read_format_rar_seek_data() function. This flaw involves an integer overflow that can ultimately lead to a double-free condition. Exploiting a double-free vulnerability can result in memory corruption, enabling an attacker to execute arbitrary code or cause a denial-of-service condition.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-415"
          ],
          "VendorSeverity": {
            "amazon": 3,
            "nvd": 4,
            "photon": 3,
            "redhat": 3,
            "ubuntu": 2
          },
          "CVSS": {
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 9.8
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:R/S:U/C:H/I:H/A:H",
              "V3Score": 7.3
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2025-5914",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370861",
            "https://github.com/libarchive/libarchive/pull/2598",
            "https://github.com/libarchive/libarchive/pull/2598/commits/196029dd0a17cd17c916eada9085839032b76ec9",
            "https://github.com/libarchive/libarchive/releases/tag/v3.8.0",
            "https://nvd.nist.gov/vuln/detail/CVE-2025-5914",
            "https://ubuntu.com/security/notices/USN-7601-1",
            "https://www.cve.org/CVERecord?id=CVE-2025-5914"
          ],
          "PublishedDate": "2025-06-09T20:15:26.123Z",
          "LastModifiedDate": "2025-08-12T11:15:27.42Z"
        },
        {
          "VulnerabilityID": "CVE-2025-49794",
          "VendorIDs": [
            "RHSA-2025:10698"
          ],
          "PkgID": "libxml2@2.9.7-19.el8_10.x86_64",
          "PkgName": "libxml2",
          "PkgIdentifier": {
            "PURL": "pkg:rpm/redhat/libxml2@2.9.7-19.el8_10?arch=x86_64\u0026distro=redhat-8.10",
            "UID": "7b608c0d4342b288"
          },
          "InstalledVersion": "2.9.7-19.el8_10",
          "FixedVersion": "2.9.7-21.el8_10.1",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:2ff76d26bc63ae58824e835b041e65a91335b77fbc45c3d628f259cce07f144f"
          },
          "SeveritySource": "redhat",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2025-49794",
          "Title": "libxml: Heap use after free (UAF) leads to Denial of service (DoS)",
          "Description": "A use-after-free vulnerability was found in libxml2. This issue occurs when parsing XPath elements under certain circumstances when the XML schematron has the \u003csch:name path=\"...\"/\u003e schema elements. This flaw allows a malicious actor to craft a malicious XML document used as input for libxml, resulting in the program's crash using libxml or other possible undefined behaviors.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-825"
          ],
          "VendorSeverity": {
            "alma": 3,
            "amazon": 3,
            "azure": 4,
            "cbl-mariner": 4,
            "oracle-oval": 3,
            "photon": 4,
            "redhat": 3,
            "rocky": 3
          },
          "CVSS": {
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:H",
              "V3Score": 9.1
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2025:10630",
            "https://access.redhat.com/errata/RHSA-2025:10698",
            "https://access.redhat.com/errata/RHSA-2025:10699",
            "https://access.redhat.com/errata/RHSA-2025:11580",
            "https://access.redhat.com/errata/RHSA-2025:12098",
            "https://access.redhat.com/errata/RHSA-2025:12099",
            "https://access.redhat.com/errata/RHSA-2025:12199",
            "https://access.redhat.com/errata/RHSA-2025:12237",
            "https://access.redhat.com/errata/RHSA-2025:12239",
            "https://access.redhat.com/errata/RHSA-2025:12240",
            "https://access.redhat.com/errata/RHSA-2025:12241",
            "https://access.redhat.com/errata/RHSA-2025:13335",
            "https://access.redhat.com/security/cve/CVE-2025-49794",
            "https://bugzilla.redhat.com/2372373",
            "https://bugzilla.redhat.com/2372385",
            "https://bugzilla.redhat.com/2372406",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2372373",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2372385",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2372406",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-49794",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-49796",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-6021",
            "https://errata.almalinux.org/9/ALSA-2025-10699.html",
            "https://errata.rockylinux.org/RLSA-2025:10698",
            "https://linux.oracle.com/cve/CVE-2025-49794.html",
            "https://linux.oracle.com/errata/ELSA-2025-12240.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2025-49794",
            "https://www.cve.org/CVERecord?id=CVE-2025-49794"
          ],
          "PublishedDate": "2025-06-16T16:15:18.997Z",
          "LastModifiedDate": "2025-08-07T09:15:27.75Z"
        },
        {
          "VulnerabilityID": "CVE-2025-49796",
          "VendorIDs": [
            "RHSA-2025:10698"
          ],
          "PkgID": "libxml2@2.9.7-19.el8_10.x86_64",
          "PkgName": "libxml2",
          "PkgIdentifier": {
            "PURL": "pkg:rpm/redhat/libxml2@2.9.7-19.el8_10?arch=x86_64\u0026distro=redhat-8.10",
            "UID": "7b608c0d4342b288"
          },
          "InstalledVersion": "2.9.7-19.el8_10",
          "FixedVersion": "2.9.7-21.el8_10.1",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:2ff76d26bc63ae58824e835b041e65a91335b77fbc45c3d628f259cce07f144f"
          },
          "SeveritySource": "redhat",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2025-49796",
          "Title": "libxml: Type confusion leads to Denial of service (DoS)",
          "Description": "A vulnerability was found in libxml2. Processing certain sch:name elements from the input XML file can trigger a memory corruption issue. This flaw allows an attacker to craft a malicious XML input file that can lead libxml to crash, resulting in a denial of service or other possible undefined behavior due to sensitive data being corrupted in memory.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-125"
          ],
          "VendorSeverity": {
            "alma": 3,
            "amazon": 3,
            "azure": 4,
            "cbl-mariner": 4,
            "oracle-oval": 3,
            "photon": 4,
            "redhat": 3,
            "rocky": 3
          },
          "CVSS": {
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:H",
              "V3Score": 9.1
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2025:10630",
            "https://access.redhat.com/errata/RHSA-2025:10698",
            "https://access.redhat.com/errata/RHSA-2025:10699",
            "https://access.redhat.com/errata/RHSA-2025:11580",
            "https://access.redhat.com/errata/RHSA-2025:12098",
            "https://access.redhat.com/errata/RHSA-2025:12099",
            "https://access.redhat.com/errata/RHSA-2025:12199",
            "https://access.redhat.com/errata/RHSA-2025:12237",
            "https://access.redhat.com/errata/RHSA-2025:12239",
            "https://access.redhat.com/errata/RHSA-2025:12240",
            "https://access.redhat.com/errata/RHSA-2025:12241",
            "https://access.redhat.com/errata/RHSA-2025:13267",
            "https://access.redhat.com/errata/RHSA-2025:13335",
            "https://access.redhat.com/security/cve/CVE-2025-49796",
            "https://bugzilla.redhat.com/2372373",
            "https://bugzilla.redhat.com/2372385",
            "https://bugzilla.redhat.com/2372406",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2372373",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2372385",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2372406",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-49794",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-49796",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-6021",
            "https://errata.almalinux.org/9/ALSA-2025-10699.html",
            "https://errata.rockylinux.org/RLSA-2025:10698",
            "https://linux.oracle.com/cve/CVE-2025-49796.html",
            "https://linux.oracle.com/errata/ELSA-2025-12240.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2025-49796",
            "https://www.cve.org/CVERecord?id=CVE-2025-49796"
          ],
          "PublishedDate": "2025-06-16T16:15:19.37Z",
          "LastModifiedDate": "2025-08-07T09:15:27.99Z"
        },
        {
          "VulnerabilityID": "CVE-2025-7425",
          "VendorIDs": [
            "RHSA-2025:12450"
          ],
          "PkgID": "libxml2@2.9.7-19.el8_10.x86_64",
          "PkgName": "libxml2",
          "PkgIdentifier": {
            "PURL": "pkg:rpm/redhat/libxml2@2.9.7-19.el8_10?arch=x86_64\u0026distro=redhat-8.10",
            "UID": "7b608c0d4342b288"
          },
          "InstalledVersion": "2.9.7-19.el8_10",
          "FixedVersion": "2.9.7-21.el8_10.2",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:2ff76d26bc63ae58824e835b041e65a91335b77fbc45c3d628f259cce07f144f"
          },
          "SeveritySource": "redhat",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2025-7425",
          "Title": "libxslt: Heap Use-After-Free in libxslt caused by atype corruption in xmlAttrPtr",
          "Description": "A flaw was found in libxslt where the attribute type, atype, flags are modified in a way that corrupts internal memory management. When XSLT functions, such as the key() process, result in tree fragments, this corruption prevents the proper cleanup of ID attributes. As a result, the system may access freed memory, causing crashes or enabling attackers to trigger heap corruption.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-416"
          ],
          "VendorSeverity": {
            "alma": 3,
            "oracle-oval": 3,
            "redhat": 3
          },
          "CVSS": {
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:L/AC:H/PR:N/UI:N/S:C/C:N/I:H/A:H",
              "V3Score": 7.8
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2025:12447",
            "https://access.redhat.com/errata/RHSA-2025:12450",
            "https://access.redhat.com/errata/RHSA-2025:13267",
            "https://access.redhat.com/errata/RHSA-2025:13308",
            "https://access.redhat.com/errata/RHSA-2025:13309",
            "https://access.redhat.com/errata/RHSA-2025:13310",
            "https://access.redhat.com/errata/RHSA-2025:13311",
            "https://access.redhat.com/errata/RHSA-2025:13312",
            "https://access.redhat.com/errata/RHSA-2025:13313",
            "https://access.redhat.com/errata/RHSA-2025:13314",
            "https://access.redhat.com/errata/RHSA-2025:13335",
            "https://access.redhat.com/errata/RHSA-2025:13464",
            "https://access.redhat.com/errata/RHSA-2025:13622",
            "https://access.redhat.com/security/cve/CVE-2025-7425",
            "https://bugzilla.redhat.com/2379274",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2379274",
            "https://errata.almalinux.org/9/ALSA-2025-12447.html",
            "https://gitlab.gnome.org/GNOME/libxslt/-/issues/140",
            "https://linux.oracle.com/cve/CVE-2025-7425.html",
            "https://linux.oracle.com/errata/ELSA-2025-12450.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2025-7425",
            "https://www.cve.org/CVERecord?id=CVE-2025-7425"
          ],
          "PublishedDate": "2025-07-10T14:15:27.877Z",
          "LastModifiedDate": "2025-08-11T15:15:28.383Z"
        },
        {
          "VulnerabilityID": "CVE-2025-6020",
          "VendorIDs": [
            "RHSA-2025:10027"
          ],
          "PkgID": "pam@1.3.1-36.el8_10.x86_64",
          "PkgName": "pam",
          "PkgIdentifier": {
            "PURL": "pkg:rpm/redhat/pam@1.3.1-36.el8_10?arch=x86_64\u0026distro=redhat-8.10",
            "UID": "79efc0d0c1c1b4ec"
          },
          "InstalledVersion": "1.3.1-36.el8_10",
          "FixedVersion": "1.3.1-37.el8_10",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:2ff76d26bc63ae58824e835b041e65a91335b77fbc45c3d628f259cce07f144f"
          },
          "SeveritySource": "redhat",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2025-6020",
          "Title": "linux-pam: Linux-pam directory Traversal",
          "Description": "A flaw was found in linux-pam. The module pam_namespace may use access user-controlled paths without proper protection, allowing local users to elevate their privileges to root via multiple symlink attacks and race conditions.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-22"
          ],
          "VendorSeverity": {
            "alma": 3,
            "amazon": 2,
            "azure": 3,
            "cbl-mariner": 3,
            "oracle-oval": 3,
            "redhat": 3,
            "rocky": 3,
            "ubuntu": 2
          },
          "CVSS": {
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 7.8
            }
          },
          "References": [
            "http://www.openwall.com/lists/oss-security/2025/06/17/1",
            "https://access.redhat.com/errata/RHSA-2025:10024",
            "https://access.redhat.com/errata/RHSA-2025:10027",
            "https://access.redhat.com/errata/RHSA-2025:10180",
            "https://access.redhat.com/errata/RHSA-2025:10354",
            "https://access.redhat.com/errata/RHSA-2025:10357",
            "https://access.redhat.com/errata/RHSA-2025:10358",
            "https://access.redhat.com/errata/RHSA-2025:10359",
            "https://access.redhat.com/errata/RHSA-2025:10361",
            "https://access.redhat.com/errata/RHSA-2025:10362",
            "https://access.redhat.com/errata/RHSA-2025:10735",
            "https://access.redhat.com/errata/RHSA-2025:10823",
            "https://access.redhat.com/errata/RHSA-2025:11386",
            "https://access.redhat.com/errata/RHSA-2025:11487",
            "https://access.redhat.com/errata/RHSA-2025:9526",
            "https://access.redhat.com/security/cve/CVE-2025-6020",
            "https://bugzilla.redhat.com/2372512",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2372512",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-6020",
            "https://errata.almalinux.org/9/ALSA-2025-9526.html",
            "https://errata.rockylinux.org/RLSA-2025:10027",
            "https://linux.oracle.com/cve/CVE-2025-6020.html",
            "https://linux.oracle.com/errata/ELSA-2025-9526.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2025-6020",
            "https://ubuntu.com/security/notices/USN-7580-1",
            "https://www.cve.org/CVERecord?id=CVE-2025-6020",
            "https://www.openwall.com/lists/oss-security/2025/06/17/1"
          ],
          "PublishedDate": "2025-06-17T13:15:21.66Z",
          "LastModifiedDate": "2025-07-21T20:15:42.027Z"
        },
        {
          "VulnerabilityID": "CVE-2025-8941",
          "PkgID": "pam@1.3.1-36.el8_10.x86_64",
          "PkgName": "pam",
          "PkgIdentifier": {
            "PURL": "pkg:rpm/redhat/pam@1.3.1-36.el8_10?arch=x86_64\u0026distro=redhat-8.10",
            "UID": "79efc0d0c1c1b4ec"
          },
          "InstalledVersion": "1.3.1-36.el8_10",
          "Status": "affected",
          "Layer": {
            "DiffID": "sha256:2ff76d26bc63ae58824e835b041e65a91335b77fbc45c3d628f259cce07f144f"
          },
          "SeveritySource": "redhat",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2025-8941",
          "Title": "linux-pam: Incomplete fix for CVE-2025-6020",
          "Description": "A flaw was found in linux-pam. The pam_namespace module may improperly handle user-controlled paths, allowing local users to exploit symlink attacks and race conditions to elevate their privileges to root. This CVE provides a \"complete\" fix for CVE-2025-6020.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-22"
          ],
          "VendorSeverity": {
            "redhat": 3
          },
          "CVSS": {
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 7.8
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2025-8941",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2388220",
            "https://nvd.nist.gov/vuln/detail/CVE-2025-8941",
            "https://www.cve.org/CVERecord?id=CVE-2025-8941"
          ],
          "PublishedDate": "2025-08-13T15:15:41.873Z",
          "LastModifiedDate": "2025-08-13T17:33:46.673Z"
        },
        {
          "VulnerabilityID": "CVE-2024-12718",
          "VendorIDs": [
            "RHSA-2025:10128"
          ],
          "PkgID": "platform-python@3.6.8-69.el8_10.x86_64",
          "PkgName": "platform-python",
          "PkgIdentifier": {
            "PURL": "pkg:rpm/redhat/platform-python@3.6.8-69.el8_10?arch=x86_64\u0026distro=redhat-8.10",
            "UID": "49522309e8ff2c1e"
          },
          "InstalledVersion": "3.6.8-69.el8_10",
          "FixedVersion": "3.6.8-70.el8_10",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:2ff76d26bc63ae58824e835b041e65a91335b77fbc45c3d628f259cce07f144f"
          },
          "SeveritySource": "redhat",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-12718",
          "Title": "cpython: python: Bypass extraction filter to modify file metadata outside extraction directory",
          "Description": "Allows modifying some file metadata (e.g. last modified) with filter=\"data\" or file permissions (chmod) with filter=\"tar\" of files outside the extraction directory.\nYou are affected by this vulnerability if using the tarfile module to extract untrusted tar archives using TarFile.extractall() or TarFile.extract() using the filter= parameter with a value of \"data\" or \"tar\". See the tarfile  extraction filters documentation https://docs.python.org/3/library/tarfile.html#tarfile-extraction-filter  for more information. Only Python versions 3.12 or later are affected by these vulnerabilities, earlier versions don't include the extraction filter feature.\n\nNote that for Python 3.14 or later the default value of filter= changed from \"no filtering\" to `\"data\", so if you are relying on this new default behavior then your usage is also affected.\n\nNote that none of these vulnerabilities significantly affect the installation of source distributions which are tar archives as source distributions already allow arbitrary code execution during the build process. However when evaluating source distributions it's important to avoid installing source distributions with suspicious links.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-22"
          ],
          "VendorSeverity": {
            "alma": 3,
            "amazon": 3,
            "bitnami": 2,
            "cbl-mariner": 2,
            "oracle-oval": 3,
            "photon": 2,
            "redhat": 3,
            "rocky": 3,
            "ubuntu": 2
          },
          "CVSS": {
            "bitnami": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
              "V3Score": 5.3
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:H/I:H/A:L",
              "V3Score": 7.6
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2025:10189",
            "https://access.redhat.com/security/cve/CVE-2024-12718",
            "https://bugzilla.redhat.com/2370010",
            "https://bugzilla.redhat.com/2370013",
            "https://bugzilla.redhat.com/2370014",
            "https://bugzilla.redhat.com/2370016",
            "https://bugzilla.redhat.com/2372426",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370010",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370013",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370014",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370016",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2372426",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-12718",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4138",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4330",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4435",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4517",
            "https://errata.almalinux.org/9/ALSA-2025-10189.html",
            "https://errata.rockylinux.org/RLSA-2025:10031",
            "https://gist.github.com/sethmlarson/52398e33eff261329a0180ac1d54f42f",
            "https://github.com/python/cpython/commit/19de092debb3d7e832e5672cc2f7b788d35951da",
            "https://github.com/python/cpython/commit/28463dba112af719df1e8b0391c46787ad756dd9",
            "https://github.com/python/cpython/commit/3612d8f51741b11f36f8fb0494d79086bac9390a",
            "https://github.com/python/cpython/commit/4633f3f497b1ff70e4a35b6fe2c907cbe2d4cb2e",
            "https://github.com/python/cpython/commit/98016f7c92aa4c1232c68bac1ed6646db31782ec",
            "https://github.com/python/cpython/commit/9c1110ef6652687d7c55f590f909720eddde965a",
            "https://github.com/python/cpython/commit/9e0ac76d96cf80b49055f6d6b9a6763fb9215c2a",
            "https://github.com/python/cpython/commit/aa9eb5f757ceff461e6e996f12c89e5d9b583b01",
            "https://github.com/python/cpython/commit/dd8f187d0746da151e0025c51680979ac5b4cfb1",
            "https://github.com/python/cpython/issues/127987",
            "https://github.com/python/cpython/issues/135034",
            "https://github.com/python/cpython/pull/135037",
            "https://linux.oracle.com/cve/CVE-2024-12718.html",
            "https://linux.oracle.com/errata/ELSA-2025-10189.html",
            "https://mail.python.org/archives/list/security-announce@python.org/thread/MAXIJJCUUMCL7ATZNDVEGGHUMQMUUKLG/",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-12718",
            "https://ubuntu.com/security/notices/USN-7583-1",
            "https://www.cve.org/CVERecord?id=CVE-2024-12718"
          ],
          "PublishedDate": "2025-06-03T13:15:20.183Z",
          "LastModifiedDate": "2025-07-24T16:15:29.157Z"
        },
        {
          "VulnerabilityID": "CVE-2025-4138",
          "VendorIDs": [
            "RHSA-2025:10128"
          ],
          "PkgID": "platform-python@3.6.8-69.el8_10.x86_64",
          "PkgName": "platform-python",
          "PkgIdentifier": {
            "PURL": "pkg:rpm/redhat/platform-python@3.6.8-69.el8_10?arch=x86_64\u0026distro=redhat-8.10",
            "UID": "49522309e8ff2c1e"
          },
          "InstalledVersion": "3.6.8-69.el8_10",
          "FixedVersion": "3.6.8-70.el8_10",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:2ff76d26bc63ae58824e835b041e65a91335b77fbc45c3d628f259cce07f144f"
          },
          "SeveritySource": "redhat",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2025-4138",
          "Title": "cpython: python: Bypassing extraction filter to create symlinks to arbitrary targets outside extraction directory",
          "Description": "Allows the extraction filter to be ignored, allowing symlink targets to point outside the destination directory, and the modification of some file metadata.\n\n\nYou are affected by this vulnerability if using the tarfile module to extract untrusted tar archives using TarFile.extractall() or TarFile.extract() using the filter= parameter with a value of \"data\" or \"tar\". See the tarfile  extraction filters documentation https://docs.python.org/3/library/tarfile.html#tarfile-extraction-filter  for more information.\n\nNote that for Python 3.14 or later the default value of filter= changed from \"no filtering\" to `\"data\", so if you are relying on this new default behavior then your usage is also affected.\n\nNote that none of these vulnerabilities significantly affect the installation of source distributions which are tar archives as source distributions already allow arbitrary code execution during the build process. However when evaluating source distributions it's important to avoid installing source distributions with suspicious links.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-22"
          ],
          "VendorSeverity": {
            "alma": 3,
            "amazon": 3,
            "bitnami": 3,
            "cbl-mariner": 3,
            "oracle-oval": 3,
            "photon": 3,
            "redhat": 3,
            "rocky": 3,
            "ubuntu": 2
          },
          "CVSS": {
            "bitnami": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
              "V3Score": 7.5
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2025:10189",
            "https://access.redhat.com/security/cve/CVE-2025-4138",
            "https://bugzilla.redhat.com/2370010",
            "https://bugzilla.redhat.com/2370013",
            "https://bugzilla.redhat.com/2370014",
            "https://bugzilla.redhat.com/2370016",
            "https://bugzilla.redhat.com/2372426",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370010",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370013",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370014",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370016",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2372426",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-12718",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4138",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4330",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4435",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4517",
            "https://errata.almalinux.org/9/ALSA-2025-10189.html",
            "https://errata.rockylinux.org/RLSA-2025:10031",
            "https://gist.github.com/sethmlarson/52398e33eff261329a0180ac1d54f42f",
            "https://github.com/python/cpython/commit/19de092debb3d7e832e5672cc2f7b788d35951da",
            "https://github.com/python/cpython/commit/28463dba112af719df1e8b0391c46787ad756dd9",
            "https://github.com/python/cpython/commit/3612d8f51741b11f36f8fb0494d79086bac9390a",
            "https://github.com/python/cpython/commit/4633f3f497b1ff70e4a35b6fe2c907cbe2d4cb2e",
            "https://github.com/python/cpython/commit/98016f7c92aa4c1232c68bac1ed6646db31782ec",
            "https://github.com/python/cpython/commit/9c1110ef6652687d7c55f590f909720eddde965a",
            "https://github.com/python/cpython/commit/9e0ac76d96cf80b49055f6d6b9a6763fb9215c2a",
            "https://github.com/python/cpython/commit/aa9eb5f757ceff461e6e996f12c89e5d9b583b01",
            "https://github.com/python/cpython/commit/dd8f187d0746da151e0025c51680979ac5b4cfb1",
            "https://github.com/python/cpython/issues/135034",
            "https://github.com/python/cpython/pull/135037",
            "https://linux.oracle.com/cve/CVE-2025-4138.html",
            "https://linux.oracle.com/errata/ELSA-2025-10189.html",
            "https://mail.python.org/archives/list/security-announce@python.org/thread/MAXIJJCUUMCL7ATZNDVEGGHUMQMUUKLG/",
            "https://nvd.nist.gov/vuln/detail/CVE-2025-4138",
            "https://ubuntu.com/security/notices/USN-7583-1",
            "https://www.cve.org/CVERecord?id=CVE-2025-4138"
          ],
          "PublishedDate": "2025-06-03T13:15:20.377Z",
          "LastModifiedDate": "2025-06-05T14:15:32.767Z"
        },
        {
          "VulnerabilityID": "CVE-2025-4517",
          "VendorIDs": [
            "RHSA-2025:10128"
          ],
          "PkgID": "platform-python@3.6.8-69.el8_10.x86_64",
          "PkgName": "platform-python",
          "PkgIdentifier": {
            "PURL": "pkg:rpm/redhat/platform-python@3.6.8-69.el8_10?arch=x86_64\u0026distro=redhat-8.10",
            "UID": "49522309e8ff2c1e"
          },
          "InstalledVersion": "3.6.8-69.el8_10",
          "FixedVersion": "3.6.8-70.el8_10",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:2ff76d26bc63ae58824e835b041e65a91335b77fbc45c3d628f259cce07f144f"
          },
          "SeveritySource": "redhat",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2025-4517",
          "Title": "python: cpython: Arbitrary writes via tarfile realpath overflow",
          "Description": "Allows arbitrary filesystem writes outside the extraction directory during extraction with filter=\"data\".\n\n\nYou are affected by this vulnerability if using the tarfile module to extract untrusted tar archives using TarFile.extractall() or TarFile.extract() using the filter= parameter with a value of \"data\" or \"tar\". See the tarfile  extraction filters documentation https://docs.python.org/3/library/tarfile.html#tarfile-extraction-filter  for more information.\n\nNote that for Python 3.14 or later the default value of filter= changed from \"no filtering\" to `\"data\", so if you are relying on this new default behavior then your usage is also affected.\n\nNote that none of these vulnerabilities significantly affect the installation of source distributions which are tar archives as source distributions already allow arbitrary code execution during the build process. However when evaluating source distributions it's important to avoid installing source distributions with suspicious links.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-22"
          ],
          "VendorSeverity": {
            "alma": 3,
            "amazon": 3,
            "azure": 3,
            "bitnami": 4,
            "cbl-mariner": 3,
            "oracle-oval": 3,
            "photon": 4,
            "redhat": 3,
            "rocky": 3,
            "ubuntu": 2
          },
          "CVSS": {
            "bitnami": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:L",
              "V3Score": 9.4
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:H/I:H/A:L",
              "V3Score": 7.6
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2025:10189",
            "https://access.redhat.com/security/cve/CVE-2025-4517",
            "https://bugzilla.redhat.com/2370010",
            "https://bugzilla.redhat.com/2370013",
            "https://bugzilla.redhat.com/2370014",
            "https://bugzilla.redhat.com/2370016",
            "https://bugzilla.redhat.com/2372426",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370010",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370013",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370014",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370016",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2372426",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-12718",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4138",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4330",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4435",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4517",
            "https://errata.almalinux.org/9/ALSA-2025-10189.html",
            "https://errata.rockylinux.org/RLSA-2025:10031",
            "https://gist.github.com/sethmlarson/52398e33eff261329a0180ac1d54f42f",
            "https://github.com/python/cpython/commit/19de092debb3d7e832e5672cc2f7b788d35951da",
            "https://github.com/python/cpython/commit/28463dba112af719df1e8b0391c46787ad756dd9",
            "https://github.com/python/cpython/commit/3612d8f51741b11f36f8fb0494d79086bac9390a",
            "https://github.com/python/cpython/commit/4633f3f497b1ff70e4a35b6fe2c907cbe2d4cb2e",
            "https://github.com/python/cpython/commit/98016f7c92aa4c1232c68bac1ed6646db31782ec",
            "https://github.com/python/cpython/commit/9c1110ef6652687d7c55f590f909720eddde965a",
            "https://github.com/python/cpython/commit/9e0ac76d96cf80b49055f6d6b9a6763fb9215c2a",
            "https://github.com/python/cpython/commit/aa9eb5f757ceff461e6e996f12c89e5d9b583b01",
            "https://github.com/python/cpython/commit/dd8f187d0746da151e0025c51680979ac5b4cfb1",
            "https://github.com/python/cpython/issues/135034",
            "https://github.com/python/cpython/pull/135037",
            "https://linux.oracle.com/cve/CVE-2025-4517.html",
            "https://linux.oracle.com/errata/ELSA-2025-10189.html",
            "https://mail.python.org/archives/list/security-announce@python.org/thread/MAXIJJCUUMCL7ATZNDVEGGHUMQMUUKLG/",
            "https://nvd.nist.gov/vuln/detail/CVE-2025-4517",
            "https://ubuntu.com/security/notices/USN-7583-1",
            "https://www.cve.org/CVERecord?id=CVE-2025-4517"
          ],
          "PublishedDate": "2025-06-03T13:15:20.837Z",
          "LastModifiedDate": "2025-06-05T14:15:33.05Z"
        },
        {
          "VulnerabilityID": "CVE-2024-12718",
          "VendorIDs": [
            "RHSA-2025:10128"
          ],
          "PkgID": "python3-libs@3.6.8-69.el8_10.x86_64",
          "PkgName": "python3-libs",
          "PkgIdentifier": {
            "PURL": "pkg:rpm/redhat/python3-libs@3.6.8-69.el8_10?arch=x86_64\u0026distro=redhat-8.10",
            "UID": "976963f9ca2308d1"
          },
          "InstalledVersion": "3.6.8-69.el8_10",
          "FixedVersion": "3.6.8-70.el8_10",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:2ff76d26bc63ae58824e835b041e65a91335b77fbc45c3d628f259cce07f144f"
          },
          "SeveritySource": "redhat",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-12718",
          "Title": "cpython: python: Bypass extraction filter to modify file metadata outside extraction directory",
          "Description": "Allows modifying some file metadata (e.g. last modified) with filter=\"data\" or file permissions (chmod) with filter=\"tar\" of files outside the extraction directory.\nYou are affected by this vulnerability if using the tarfile module to extract untrusted tar archives using TarFile.extractall() or TarFile.extract() using the filter= parameter with a value of \"data\" or \"tar\". See the tarfile  extraction filters documentation https://docs.python.org/3/library/tarfile.html#tarfile-extraction-filter  for more information. Only Python versions 3.12 or later are affected by these vulnerabilities, earlier versions don't include the extraction filter feature.\n\nNote that for Python 3.14 or later the default value of filter= changed from \"no filtering\" to `\"data\", so if you are relying on this new default behavior then your usage is also affected.\n\nNote that none of these vulnerabilities significantly affect the installation of source distributions which are tar archives as source distributions already allow arbitrary code execution during the build process. However when evaluating source distributions it's important to avoid installing source distributions with suspicious links.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-22"
          ],
          "VendorSeverity": {
            "alma": 3,
            "amazon": 3,
            "bitnami": 2,
            "cbl-mariner": 2,
            "oracle-oval": 3,
            "photon": 2,
            "redhat": 3,
            "rocky": 3,
            "ubuntu": 2
          },
          "CVSS": {
            "bitnami": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
              "V3Score": 5.3
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:H/I:H/A:L",
              "V3Score": 7.6
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2025:10189",
            "https://access.redhat.com/security/cve/CVE-2024-12718",
            "https://bugzilla.redhat.com/2370010",
            "https://bugzilla.redhat.com/2370013",
            "https://bugzilla.redhat.com/2370014",
            "https://bugzilla.redhat.com/2370016",
            "https://bugzilla.redhat.com/2372426",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370010",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370013",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370014",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370016",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2372426",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-12718",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4138",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4330",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4435",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4517",
            "https://errata.almalinux.org/9/ALSA-2025-10189.html",
            "https://errata.rockylinux.org/RLSA-2025:10031",
            "https://gist.github.com/sethmlarson/52398e33eff261329a0180ac1d54f42f",
            "https://github.com/python/cpython/commit/19de092debb3d7e832e5672cc2f7b788d35951da",
            "https://github.com/python/cpython/commit/28463dba112af719df1e8b0391c46787ad756dd9",
            "https://github.com/python/cpython/commit/3612d8f51741b11f36f8fb0494d79086bac9390a",
            "https://github.com/python/cpython/commit/4633f3f497b1ff70e4a35b6fe2c907cbe2d4cb2e",
            "https://github.com/python/cpython/commit/98016f7c92aa4c1232c68bac1ed6646db31782ec",
            "https://github.com/python/cpython/commit/9c1110ef6652687d7c55f590f909720eddde965a",
            "https://github.com/python/cpython/commit/9e0ac76d96cf80b49055f6d6b9a6763fb9215c2a",
            "https://github.com/python/cpython/commit/aa9eb5f757ceff461e6e996f12c89e5d9b583b01",
            "https://github.com/python/cpython/commit/dd8f187d0746da151e0025c51680979ac5b4cfb1",
            "https://github.com/python/cpython/issues/127987",
            "https://github.com/python/cpython/issues/135034",
            "https://github.com/python/cpython/pull/135037",
            "https://linux.oracle.com/cve/CVE-2024-12718.html",
            "https://linux.oracle.com/errata/ELSA-2025-10189.html",
            "https://mail.python.org/archives/list/security-announce@python.org/thread/MAXIJJCUUMCL7ATZNDVEGGHUMQMUUKLG/",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-12718",
            "https://ubuntu.com/security/notices/USN-7583-1",
            "https://www.cve.org/CVERecord?id=CVE-2024-12718"
          ],
          "PublishedDate": "2025-06-03T13:15:20.183Z",
          "LastModifiedDate": "2025-07-24T16:15:29.157Z"
        },
        {
          "VulnerabilityID": "CVE-2025-4138",
          "VendorIDs": [
            "RHSA-2025:10128"
          ],
          "PkgID": "python3-libs@3.6.8-69.el8_10.x86_64",
          "PkgName": "python3-libs",
          "PkgIdentifier": {
            "PURL": "pkg:rpm/redhat/python3-libs@3.6.8-69.el8_10?arch=x86_64\u0026distro=redhat-8.10",
            "UID": "976963f9ca2308d1"
          },
          "InstalledVersion": "3.6.8-69.el8_10",
          "FixedVersion": "3.6.8-70.el8_10",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:2ff76d26bc63ae58824e835b041e65a91335b77fbc45c3d628f259cce07f144f"
          },
          "SeveritySource": "redhat",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2025-4138",
          "Title": "cpython: python: Bypassing extraction filter to create symlinks to arbitrary targets outside extraction directory",
          "Description": "Allows the extraction filter to be ignored, allowing symlink targets to point outside the destination directory, and the modification of some file metadata.\n\n\nYou are affected by this vulnerability if using the tarfile module to extract untrusted tar archives using TarFile.extractall() or TarFile.extract() using the filter= parameter with a value of \"data\" or \"tar\". See the tarfile  extraction filters documentation https://docs.python.org/3/library/tarfile.html#tarfile-extraction-filter  for more information.\n\nNote that for Python 3.14 or later the default value of filter= changed from \"no filtering\" to `\"data\", so if you are relying on this new default behavior then your usage is also affected.\n\nNote that none of these vulnerabilities significantly affect the installation of source distributions which are tar archives as source distributions already allow arbitrary code execution during the build process. However when evaluating source distributions it's important to avoid installing source distributions with suspicious links.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-22"
          ],
          "VendorSeverity": {
            "alma": 3,
            "amazon": 3,
            "bitnami": 3,
            "cbl-mariner": 3,
            "oracle-oval": 3,
            "photon": 3,
            "redhat": 3,
            "rocky": 3,
            "ubuntu": 2
          },
          "CVSS": {
            "bitnami": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
              "V3Score": 7.5
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2025:10189",
            "https://access.redhat.com/security/cve/CVE-2025-4138",
            "https://bugzilla.redhat.com/2370010",
            "https://bugzilla.redhat.com/2370013",
            "https://bugzilla.redhat.com/2370014",
            "https://bugzilla.redhat.com/2370016",
            "https://bugzilla.redhat.com/2372426",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370010",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370013",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370014",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370016",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2372426",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-12718",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4138",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4330",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4435",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4517",
            "https://errata.almalinux.org/9/ALSA-2025-10189.html",
            "https://errata.rockylinux.org/RLSA-2025:10031",
            "https://gist.github.com/sethmlarson/52398e33eff261329a0180ac1d54f42f",
            "https://github.com/python/cpython/commit/19de092debb3d7e832e5672cc2f7b788d35951da",
            "https://github.com/python/cpython/commit/28463dba112af719df1e8b0391c46787ad756dd9",
            "https://github.com/python/cpython/commit/3612d8f51741b11f36f8fb0494d79086bac9390a",
            "https://github.com/python/cpython/commit/4633f3f497b1ff70e4a35b6fe2c907cbe2d4cb2e",
            "https://github.com/python/cpython/commit/98016f7c92aa4c1232c68bac1ed6646db31782ec",
            "https://github.com/python/cpython/commit/9c1110ef6652687d7c55f590f909720eddde965a",
            "https://github.com/python/cpython/commit/9e0ac76d96cf80b49055f6d6b9a6763fb9215c2a",
            "https://github.com/python/cpython/commit/aa9eb5f757ceff461e6e996f12c89e5d9b583b01",
            "https://github.com/python/cpython/commit/dd8f187d0746da151e0025c51680979ac5b4cfb1",
            "https://github.com/python/cpython/issues/135034",
            "https://github.com/python/cpython/pull/135037",
            "https://linux.oracle.com/cve/CVE-2025-4138.html",
            "https://linux.oracle.com/errata/ELSA-2025-10189.html",
            "https://mail.python.org/archives/list/security-announce@python.org/thread/MAXIJJCUUMCL7ATZNDVEGGHUMQMUUKLG/",
            "https://nvd.nist.gov/vuln/detail/CVE-2025-4138",
            "https://ubuntu.com/security/notices/USN-7583-1",
            "https://www.cve.org/CVERecord?id=CVE-2025-4138"
          ],
          "PublishedDate": "2025-06-03T13:15:20.377Z",
          "LastModifiedDate": "2025-06-05T14:15:32.767Z"
        },
        {
          "VulnerabilityID": "CVE-2025-4517",
          "VendorIDs": [
            "RHSA-2025:10128"
          ],
          "PkgID": "python3-libs@3.6.8-69.el8_10.x86_64",
          "PkgName": "python3-libs",
          "PkgIdentifier": {
            "PURL": "pkg:rpm/redhat/python3-libs@3.6.8-69.el8_10?arch=x86_64\u0026distro=redhat-8.10",
            "UID": "976963f9ca2308d1"
          },
          "InstalledVersion": "3.6.8-69.el8_10",
          "FixedVersion": "3.6.8-70.el8_10",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:2ff76d26bc63ae58824e835b041e65a91335b77fbc45c3d628f259cce07f144f"
          },
          "SeveritySource": "redhat",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2025-4517",
          "Title": "python: cpython: Arbitrary writes via tarfile realpath overflow",
          "Description": "Allows arbitrary filesystem writes outside the extraction directory during extraction with filter=\"data\".\n\n\nYou are affected by this vulnerability if using the tarfile module to extract untrusted tar archives using TarFile.extractall() or TarFile.extract() using the filter= parameter with a value of \"data\" or \"tar\". See the tarfile  extraction filters documentation https://docs.python.org/3/library/tarfile.html#tarfile-extraction-filter  for more information.\n\nNote that for Python 3.14 or later the default value of filter= changed from \"no filtering\" to `\"data\", so if you are relying on this new default behavior then your usage is also affected.\n\nNote that none of these vulnerabilities significantly affect the installation of source distributions which are tar archives as source distributions already allow arbitrary code execution during the build process. However when evaluating source distributions it's important to avoid installing source distributions with suspicious links.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-22"
          ],
          "VendorSeverity": {
            "alma": 3,
            "amazon": 3,
            "azure": 3,
            "bitnami": 4,
            "cbl-mariner": 3,
            "oracle-oval": 3,
            "photon": 4,
            "redhat": 3,
            "rocky": 3,
            "ubuntu": 2
          },
          "CVSS": {
            "bitnami": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:L",
              "V3Score": 9.4
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:H/I:H/A:L",
              "V3Score": 7.6
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2025:10189",
            "https://access.redhat.com/security/cve/CVE-2025-4517",
            "https://bugzilla.redhat.com/2370010",
            "https://bugzilla.redhat.com/2370013",
            "https://bugzilla.redhat.com/2370014",
            "https://bugzilla.redhat.com/2370016",
            "https://bugzilla.redhat.com/2372426",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370010",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370013",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370014",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2370016",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2372426",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-12718",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4138",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4330",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4435",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4517",
            "https://errata.almalinux.org/9/ALSA-2025-10189.html",
            "https://errata.rockylinux.org/RLSA-2025:10031",
            "https://gist.github.com/sethmlarson/52398e33eff261329a0180ac1d54f42f",
            "https://github.com/python/cpython/commit/19de092debb3d7e832e5672cc2f7b788d35951da",
            "https://github.com/python/cpython/commit/28463dba112af719df1e8b0391c46787ad756dd9",
            "https://github.com/python/cpython/commit/3612d8f51741b11f36f8fb0494d79086bac9390a",
            "https://github.com/python/cpython/commit/4633f3f497b1ff70e4a35b6fe2c907cbe2d4cb2e",
            "https://github.com/python/cpython/commit/98016f7c92aa4c1232c68bac1ed6646db31782ec",
            "https://github.com/python/cpython/commit/9c1110ef6652687d7c55f590f909720eddde965a",
            "https://github.com/python/cpython/commit/9e0ac76d96cf80b49055f6d6b9a6763fb9215c2a",
            "https://github.com/python/cpython/commit/aa9eb5f757ceff461e6e996f12c89e5d9b583b01",
            "https://github.com/python/cpython/commit/dd8f187d0746da151e0025c51680979ac5b4cfb1",
            "https://github.com/python/cpython/issues/135034",
            "https://github.com/python/cpython/pull/135037",
            "https://linux.oracle.com/cve/CVE-2025-4517.html",
            "https://linux.oracle.com/errata/ELSA-2025-10189.html",
            "https://mail.python.org/archives/list/security-announce@python.org/thread/MAXIJJCUUMCL7ATZNDVEGGHUMQMUUKLG/",
            "https://nvd.nist.gov/vuln/detail/CVE-2025-4517",
            "https://ubuntu.com/security/notices/USN-7583-1",
            "https://www.cve.org/CVERecord?id=CVE-2025-4517"
          ],
          "PublishedDate": "2025-06-03T13:15:20.837Z",
          "LastModifiedDate": "2025-06-05T14:15:33.05Z"
        },
        {
          "VulnerabilityID": "CVE-2025-6965",
          "VendorIDs": [
            "RHSA-2025:12010"
          ],
          "PkgID": "sqlite-libs@3.26.0-19.el8_9.x86_64",
          "PkgName": "sqlite-libs",
          "PkgIdentifier": {
            "PURL": "pkg:rpm/redhat/sqlite-libs@3.26.0-19.el8_9?arch=x86_64\u0026distro=redhat-8.10",
            "UID": "a50ad3a1cb22b1f2"
          },
          "InstalledVersion": "3.26.0-19.el8_9",
          "FixedVersion": "3.26.0-20.el8_10",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:2ff76d26bc63ae58824e835b041e65a91335b77fbc45c3d628f259cce07f144f"
          },
          "SeveritySource": "redhat",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2025-6965",
          "Title": "sqlite: Integer Truncation in SQLite",
          "Description": "There exists a vulnerability in SQLite versions before 3.50.2 where the number of aggregate terms could exceed the number of columns available. This could lead to a memory corruption issue. We recommend upgrading to version 3.50.2 or above.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-197"
          ],
          "VendorSeverity": {
            "alma": 3,
            "amazon": 2,
            "bitnami": 3,
            "cbl-mariner": 3,
            "nvd": 4,
            "oracle-oval": 3,
            "redhat": 3,
            "rocky": 3,
            "ubuntu": 2
          },
          "CVSS": {
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 9.8
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:C/C:L/I:H/A:L",
              "V3Score": 7.7
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2025:11992",
            "https://access.redhat.com/security/cve/CVE-2025-6965",
            "https://bugzilla.redhat.com/2380149",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2380149",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-6965",
            "https://errata.almalinux.org/9/ALSA-2025-11992.html",
            "https://errata.rockylinux.org/RLSA-2025:12010",
            "https://linux.oracle.com/cve/CVE-2025-6965.html",
            "https://linux.oracle.com/errata/ELSA-2025-12349.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2025-6965",
            "https://ubuntu.com/security/notices/USN-7676-1",
            "https://ubuntu.com/security/notices/USN-7679-1",
            "https://www.cve.org/CVERecord?id=CVE-2025-6965",
            "https://www.sqlite.org/src/info/5508b56fd24016c13981ec280ecdd833007c9d8dd595edb295b984c2b487b5c8"
          ],
          "PublishedDate": "2025-07-15T14:15:31.08Z",
          "LastModifiedDate": "2025-07-22T17:06:21.51Z"
        }
      ]
    }
  ]
}